# Generated by Django 5.2 on 2026-05-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("foto", models.CharField(blank=True, max_length=255, null=True)),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("cedula", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "papel",
                    models.CharField(
                        choices=[
                            ("Administrador", "Administrador"),
                            ("Despachante Oficial", "Despachante Oficial"),
                            ("Operador", "Operador"),
                            ("Visualizador", "Visualizador"),
                        ],
                        default="Despachante Oficial",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Ativo", "Ativo"),
                            ("Inativo", "Inativo"),
                            ("Suspenso", "Suspenso"),
                        ],
                        default="Ativo",
                        max_length=10,
                    ),
                ),
                ("sso_portal_id", models.IntegerField(blank=True, null=True)),
                ("ultimo_acesso", models.DateTimeField(blank=True, null=True)),
                ("nif", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Utilizador",
                "verbose_name_plural": "Utilizadores",
                "db_table": "usuarios",
                "managed": True,
            },
        ),
    ]
