# Generated by Django 5.2 on 2026-05-31 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="usuario",
            name="idx_usuario_papel_status",
        ),
    ]
