# Generated by Django 5.2 on 2026-06-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_critical_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="is_secretario",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuario",
            name="is_vice_secretario",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="papel",
            field=models.CharField(
                choices=[
                    ("Administrador", "Administrador"),
                    ("Despachante Oficial", "Despachante Oficial"),
                    ("Operador", "Operador"),
                    ("Visualizador", "Visualizador"),
                ],
                default="Despachante Oficial",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="status",
            field=models.CharField(
                choices=[
                    ("Ativo", "Ativo"),
                    ("Inativo", "Inativo"),
                    ("Suspenso", "Suspenso"),
                ],
                default="Ativo",
                max_length=10,
            ),
        ),
    ]
