# Generated by Django 5.2 on 2026-06-02 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanca", "0016_categoriamembro_isencaomembro_tipoquota_and_more"),
        ("users", "0005_add_secretario_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanca.categoriamembro",
            ),
        ),
    ]
