# Generated by Django 5.2 on 2026-06-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "governanca",
            "0020_alter_assembleia_data_hora_alter_assembleia_status_and_more",
        ),
        ("users", "0006_usuario_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="papel",
            field=models.CharField(
                choices=[
                    ("Administrador", "Administrador"),
                    ("Despachante Oficial", "Despachante Oficial"),
                    ("Operador", "Operador"),
                    ("Visualizador", "Visualizador"),
                ],
                db_index=True,
                default="Despachante Oficial",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="status",
            field=models.CharField(
                choices=[
                    ("Ativo", "Ativo"),
                    ("Inativo", "Inativo"),
                    ("Suspenso", "Suspenso"),
                ],
                db_index=True,
                default="Ativo",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(
                fields=["papel", "status"], name="idx_usuario_papel_status"
            ),
        ),
    ]
