# Generated by Django 5.2 on 2026-06-03 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_usuario_papel_alter_usuario_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
                "db_table": "cargos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="UsuarioCargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("atribuido_em", models.DateTimeField(auto_now_add=True)),
                (
                    "atribuido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atribuicoes_cargo",
                        to="users.usuario",
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos",
                        to="users.cargo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos_cargo",
                        to="users.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vinculo de Cargo",
                "verbose_name_plural": "Vinculos de Cargos",
                "db_table": "usuarios_cargos",
                "unique_together": {("usuario", "cargo")},
            },
        ),
        migrations.AddField(
            model_name="usuario",
            name="cargos",
            field=models.ManyToManyField(
                blank=True,
                related_name="membros",
                through="users.UsuarioCargo",
                through_fields=("usuario", "cargo"),
                to="users.cargo",
            ),
        ),
    ]
