# Generated by Django 5.2 on 2026-06-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_cargo_model_e_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="sistema",
            field=models.BooleanField(
                default=False,
                help_text="Cargo automático do sistema (não pode ser removido manualmente)",
            ),
        ),
    ]
