# Generated by Django 5.2 on 2026-06-03 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_cargo_sistema_e_direcao"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usuariocargo",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="usuariocargo",
            name="cargo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vinculo",
                to="users.cargo",
            ),
        ),
    ]
