# Generated by Django 5.2 on 2026-06-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_cargo_unique_por_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="nome",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
