# Generated by Django 5.2 on 2026-06-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_usuario_nome"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permissao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.SlugField(
                        help_text="Identificador único (ex: ver_secretaria, gerir_quotas)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, default="")),
                (
                    "grupo",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Agrupamento visual (ex: Secretaria, Financeiro)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Permissão",
                "verbose_name_plural": "Permissões",
                "db_table": "permissoes",
                "ordering": ["grupo", "nome"],
            },
        ),
        migrations.AddField(
            model_name="cargo",
            name="permissoes",
            field=models.ManyToManyField(
                blank=True, related_name="cargos", to="users.permissao"
            ),
        ),
    ]
