# Generated by Django 5.2 on 2026-06-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_seed_permissoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Acesso ao Admin"),
        ),
        migrations.AddField(
            model_name="usuario",
            name="is_superuser",
            field=models.BooleanField(default=False, verbose_name="Superutilizador"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="papel",
            field=models.CharField(
                choices=[
                    ("Administrador", "Administrador"),
                    ("Gestor Financeiro", "Gestor Financeiro"),
                    ("Despachante Oficial", "Despachante Oficial"),
                    ("Operador", "Operador"),
                    ("Visualizador", "Visualizador"),
                ],
                db_index=True,
                default="Despachante Oficial",
                max_length=50,
            ),
        ),
    ]
