# Generated by Django 5.2 on 2026-06-10 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_usuario_is_staff_usuario_is_superuser_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CicloAvaliacaoInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("periodo_inicio", models.DateField()),
                ("periodo_fim", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Aberto", "Aberto"),
                            ("Em Curso", "Em Curso"),
                            ("Encerrado", "Encerrado"),
                        ],
                        default="Aberto",
                        max_length=10,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Ciclo de Avaliação Institucional",
                "verbose_name_plural": "Ciclos de Avaliação Institucionais",
                "db_table": "ciclos_avaliacao_institucionais",
                "ordering": ["-periodo_inicio"],
            },
        ),
        migrations.AddField(
            model_name="usuario",
            name="area_actuacao",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="usuario",
            name="cargo_personalizado",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="usuario",
            name="permissoes_diretas",
            field=models.ManyToManyField(
                blank=True, related_name="usuarios_diretos", to="users.permissao"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="papel",
            field=models.CharField(
                choices=[
                    ("Administrador", "Administrador"),
                    ("Gestor Financeiro", "Gestor Financeiro"),
                    ("Despachante Oficial", "Despachante Oficial"),
                    ("Operador", "Operador"),
                    ("Colaborador Institucional", "Colaborador Institucional"),
                    ("Visualizador", "Visualizador"),
                ],
                db_index=True,
                default="Despachante Oficial",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ColaboradorInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("telefone", models.CharField(blank=True, default="", max_length=30)),
                (
                    "area_actuacao",
                    models.CharField(
                        choices=[
                            ("Informática", "Informática"),
                            ("Limpeza", "Limpeza"),
                            ("Administrativo", "Administrativo"),
                            ("Financeiro", "Financeiro"),
                            ("Jurídico", "Jurídico"),
                            ("Recursos Humanos", "Recursos Humanos"),
                            ("Comunicação", "Comunicação"),
                            ("Outro", "Outro"),
                        ],
                        default="Administrativo",
                        max_length=50,
                    ),
                ),
                ("data_admissao", models.DateField(blank=True, null=True)),
                (
                    "salario_base",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Ativo", "Ativo"),
                            ("Inativo", "Inativo"),
                            ("Suspenso", "Suspenso"),
                            ("Ferias", "De Férias"),
                        ],
                        default="Ativo",
                        max_length=10,
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="colaboradores_institucionais/fotos/",
                    ),
                ),
                ("observacoes", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colaborador_institucional",
                        to="users.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colaborador Institucional",
                "verbose_name_plural": "Colaboradores Institucionais",
                "db_table": "colaboradores_institucionais",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="FeriasInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("motivo", models.TextField(blank=True, default="")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Aprovado", "Aprovado"),
                            ("Rejeitado", "Rejeitado"),
                        ],
                        default="Pendente",
                        max_length=10,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos_ferias",
                        to="users.colaboradorinstitucional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Férias Institucional",
                "verbose_name_plural": "Férias Institucionais",
                "db_table": "ferias_institucionais",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ProcessamentoSalarialInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.PositiveSmallIntegerField()),
                ("ano", models.PositiveSmallIntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Rascunho", "Rascunho"),
                            ("Processado", "Processado"),
                            ("Pago", "Pago"),
                        ],
                        default="Rascunho",
                        max_length=15,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("processado_em", models.DateTimeField(blank=True, null=True)),
                ("pdf_gerado", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Processamento Salarial Institucional",
                "verbose_name_plural": "Processamentos Salariais Institucionais",
                "db_table": "processamentos_salariais_institucionais",
                "ordering": ["-ano", "-mes"],
                "unique_together": {("mes", "ano")},
            },
        ),
        migrations.CreateModel(
            name="AvaliacaoInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pontualidade", models.PositiveSmallIntegerField(default=3)),
                ("produtividade", models.PositiveSmallIntegerField(default=3)),
                ("qualidade_trabalho", models.PositiveSmallIntegerField(default=3)),
                ("trabalho_equipa", models.PositiveSmallIntegerField(default=3)),
                ("iniciativa", models.PositiveSmallIntegerField(default=3)),
                (
                    "nota_global",
                    models.DecimalField(decimal_places=1, default=3, max_digits=3),
                ),
                ("pontos_fortes", models.TextField(blank=True, default="")),
                ("pontos_melhoria", models.TextField(blank=True, default="")),
                ("plano_desenvolvimento", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="users.cicloavaliacaoinstitucional",
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="users.colaboradorinstitucional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação Institucional",
                "verbose_name_plural": "Avaliações Institucionais",
                "db_table": "avaliacoes_institucionais",
                "unique_together": {("ciclo", "colaborador")},
            },
        ),
        migrations.CreateModel(
            name="PresencaInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Entrada", "Entrada"),
                            ("Saida", "Saída"),
                            ("Hora_Extra", "Hora Extra"),
                            ("Falta", "Falta"),
                            ("Falta_Justificada", "Falta Justificada"),
                            ("Ferias", "Férias"),
                            ("Feriado", "Feriado"),
                        ],
                        default="Entrada",
                        max_length=20,
                    ),
                ),
                ("hora_entrada", models.TimeField(blank=True, null=True)),
                ("hora_saida", models.TimeField(blank=True, null=True)),
                (
                    "horas_extras",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                ("justificacao", models.TextField(blank=True, default="")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Aprovado", "Aprovado"),
                            ("Rejeitado", "Rejeitado"),
                        ],
                        default="Pendente",
                        max_length=10,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presencas",
                        to="users.colaboradorinstitucional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presença Institucional",
                "verbose_name_plural": "Presenças Institucionais",
                "db_table": "presencas_institucionais",
                "ordering": ["-data"],
                "unique_together": {("colaborador", "data")},
            },
        ),
        migrations.CreateModel(
            name="ReciboSalarialInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salario_base",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "subsidio_alimentacao",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "subsidio_transporte",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "outros_subsidios",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "horas_extras_valor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "irt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "inss_trabalhador",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "outros_descontos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("observacoes", models.TextField(blank=True, default="")),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recibos",
                        to="users.colaboradorinstitucional",
                    ),
                ),
                (
                    "processamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recibos",
                        to="users.processamentosalarialinstitucional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recibo Salarial Institucional",
                "verbose_name_plural": "Recibos Salariais Institucionais",
                "db_table": "recibos_salariais_institucionais",
                "unique_together": {("processamento", "colaborador")},
            },
        ),
    ]
