# Generated by Django 5.2 on 2026-06-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_seed_permissoes_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="permissao",
            name="icone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
