# Generated by Django 5.2 on 2026-06-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_add_icone_to_permissao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaboradorinstitucional",
            name="area_actuacao",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
