# Generated by Django 5.2 on 2026-06-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_add_ver_relatorios_operacionais"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="cargos",
        ),
        migrations.RemoveField(
            model_name="usuariocargo",
            name="cargo",
        ),
        migrations.RemoveField(
            model_name="usuariocargo",
            name="atribuido_por",
        ),
        migrations.RemoveField(
            model_name="usuariocargo",
            name="usuario",
        ),
        migrations.DeleteModel(
            name="Cargo",
        ),
        migrations.DeleteModel(
            name="UsuarioCargo",
        ),
    ]
