# Generated by Django 5.2 on 2026-06-11 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_seed_permissoes_v3"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogAtividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario_nome",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Nome do Utilizador",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "accao",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGIN_FALHA", "Tentativa de login falhada"),
                            ("LOGOUT", "Logout"),
                            ("SESSAO_EXPIRADA", "Sessão expirada"),
                            ("VIEW", "Visualização"),
                            ("CREATE", "Criação"),
                            ("EDIT", "Edição"),
                            ("DELETE", "Eliminação"),
                            ("CANCEL", "Cancelamento"),
                            ("APPROVE", "Aprovação"),
                            ("REJECT", "Rejeição"),
                            ("SEND_EMAIL", "Envio de Email"),
                            ("EXPORT", "Exportação"),
                            ("DOWNLOAD", "Download"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "modulo",
                    models.CharField(
                        choices=[
                            ("users", "Utilizadores"),
                            ("clientes", "Clientes"),
                            ("financeiro", "Financeiro"),
                            ("governanca", "Governança"),
                            ("rh", "Recursos Humanos"),
                            ("aduaneiro", "Aduaneiro"),
                            ("sistema", "Sistema"),
                        ],
                        max_length=20,
                        verbose_name="Módulo",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, default="", verbose_name="Descrição"),
                ),
                (
                    "modelo_alvo",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Modelo Alvo",
                    ),
                ),
                (
                    "id_alvo",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID do Registo"
                    ),
                ),
                (
                    "detalhes",
                    models.JSONField(blank=True, null=True, verbose_name="Detalhes"),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User-Agent"),
                ),
                (
                    "url",
                    models.TextField(
                        blank=True, default="", verbose_name="URL Acedido"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Data/Hora"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_atividade",
                        to="users.usuario",
                        verbose_name="Utilizador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Atividade",
                "verbose_name_plural": "Logs de Atividade",
                "db_table": "logs_atividade",
                "ordering": ["-created_at"],
            },
        ),
    ]
