# Generated by Django 5.2 on 2026-06-11 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_logatividade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funcao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permissoes",
                    models.ManyToManyField(
                        blank=True, related_name="funcoes", to="users.permissao"
                    ),
                ),
            ],
            options={
                "verbose_name": "Função",
                "verbose_name_plural": "Funções",
                "db_table": "funcoes",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="usuario",
            name="funcao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="users.funcao",
            ),
        ),
    ]
