# Generated by Django 5.2 on 2026-06-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_add_aprovar_requisicao_permissao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="cedula",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
