# Generated by Django 5.2 on 2026-06-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_add_cedula_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cicloavaliacaoinstitucional",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Aberto", "Aberto"),
                    ("Em Curso", "Em Curso"),
                    ("Encerrado", "Encerrado"),
                ],
                db_index=True,
                default="Aberto",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="colaboradorinstitucional",
            name="area_actuacao",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="colaboradorinstitucional",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Ativo", "Ativo"),
                    ("Inativo", "Inativo"),
                    ("Suspenso", "Suspenso"),
                    ("Ferias", "De Férias"),
                ],
                db_index=True,
                default="Ativo",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="colaboradorinstitucional",
            name="nome",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="feriasinstitucional",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aprovado", "Aprovado"),
                    ("Rejeitado", "Rejeitado"),
                ],
                db_index=True,
                default="Pendente",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="presencainstitucional",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aprovado", "Aprovado"),
                    ("Rejeitado", "Rejeitado"),
                ],
                db_index=True,
                default="Pendente",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="processamentosalarialinstitucional",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Rascunho", "Rascunho"),
                    ("Processado", "Processado"),
                    ("Pago", "Pago"),
                ],
                db_index=True,
                default="Rascunho",
                max_length=15,
            ),
        ),
    ]
