# Generated by Django 5.2 on 2026-06-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_add_db_index_to_query_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="papel",
            field=models.CharField(
                choices=[
                    ("Administrador", "Administrador"),
                    ("Despachante Oficial", "Despachante Oficial"),
                    ("Colaborador Institucional", "Colaborador Institucional"),
                    ("Visualizador", "Visualizador"),
                ],
                db_index=True,
                default="Despachante Oficial",
                max_length=50,
            ),
        ),
    ]
