# Generated by Django 5.2 on 2026-06-14 22:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_add_ser_membro_mesa_permissao"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidaturaInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("telefone", models.CharField(blank=True, default="", max_length=30)),
                (
                    "cv",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="candidaturas_institucionais/cv/",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Recebida", "Recebida"),
                            ("Em Análise", "Em Análise"),
                            ("Entrevista", "Entrevista"),
                            ("Aprovado", "Aprovado"),
                            ("Rejeitado", "Rejeitado"),
                        ],
                        db_index=True,
                        default="Recebida",
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Candidatura Institucional",
                "verbose_name_plural": "Candidaturas Institucionais",
                "db_table": "candidaturas_institucionais",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="VagaInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "departamento",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("descricao", models.TextField(blank=True, default="")),
                ("requisitos", models.TextField(blank=True, default="")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Aberta", "Aberta"),
                            ("Em Análise", "Em Análise"),
                            ("Encerrada", "Encerrada"),
                            ("Cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="Aberta",
                        max_length=20,
                    ),
                ),
                (
                    "link_externo",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "vagas_numero",
                    models.PositiveIntegerField(default=1, verbose_name="Nº de Vagas"),
                ),
                (
                    "salario_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salario_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("data_encerramento", models.DateField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vaga Institucional",
                "verbose_name_plural": "Vagas Institucionais",
                "db_table": "vagas_institucionais",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddField(
            model_name="recibosalarialinstitucional",
            name="inss_entidade",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name="EntrevistaInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Presencial", "Presencial"),
                            ("Online", "Online"),
                            ("Telefónica", "Telefónica"),
                        ],
                        default="Presencial",
                        max_length=20,
                    ),
                ),
                (
                    "local_link",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "entrevistador",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Aprovado", "Aprovado"),
                            ("Reprovado", "Reprovado"),
                        ],
                        default="Pendente",
                        max_length=20,
                    ),
                ),
                (
                    "nota",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("observacoes", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "candidatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrevistas",
                        to="users.candidaturainstitucional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrevista Institucional",
                "verbose_name_plural": "Entrevistas Institucionais",
                "db_table": "entrevistas_institucionais",
                "ordering": ["-data_hora"],
            },
        ),
        migrations.CreateModel(
            name="MetricaAvaliacaoInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True, default="")),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metricas",
                        to="users.cicloavaliacaoinstitucional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Métrica de Avaliação Institucional",
                "verbose_name_plural": "Métricas de Avaliação Institucionais",
                "db_table": "metricas_avaliacao_institucionais",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="PlanoIntegracaoInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim_prevista", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Em Curso", "Em Curso"),
                            ("Concluído", "Concluído"),
                        ],
                        default="Pendente",
                        max_length=20,
                    ),
                ),
                (
                    "responsavel",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("notas", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "candidatura",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plano_integracao",
                        to="users.candidaturainstitucional",
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planos_integracao",
                        to="users.colaboradorinstitucional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano de Integração Institucional",
                "verbose_name_plural": "Planos de Integração Institucionais",
                "db_table": "planos_integracao_institucionais",
            },
        ),
        migrations.CreateModel(
            name="SubsidioInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Subsídio"),
                ),
                (
                    "codigo",
                    models.CharField(max_length=20, verbose_name="Código Interno"),
                ),
                (
                    "tipo_calculo",
                    models.CharField(
                        choices=[
                            ("FIXO", "Valor Fixo"),
                            ("PERCENTUAL", "Percentual do Salário"),
                            ("DIAS_TRABALHO", "Por Dias de Trabalho"),
                            ("DEPENDENTES", "Por Número de Dependentes"),
                        ],
                        default="FIXO",
                        max_length=20,
                    ),
                ),
                (
                    "valor_padrao",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valor Padrão",
                    ),
                ),
                (
                    "percentual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Percentual (%)",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "obrigatorio",
                    models.BooleanField(
                        default=False, verbose_name="Obrigatório para Todos"
                    ),
                ),
                (
                    "apenas_especificos",
                    models.BooleanField(
                        default=False,
                        verbose_name="Apenas para colaboradores específicos",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "colaboradores_especificos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="subsidios_especificos",
                        to="users.colaboradorinstitucional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subsídio Institucional",
                "verbose_name_plural": "Subsídios Institucionais",
                "db_table": "subsidios_institucionais",
                "ordering": ["codigo"],
                "unique_together": {("codigo",)},
            },
        ),
        migrations.CreateModel(
            name="TarefaIntegracaoInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("concluida", models.BooleanField(default=False)),
                (
                    "responsavel",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("prazo", models.DateField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "plano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarefas",
                        to="users.planointegracaoinstitucional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarefa de Integração Institucional",
                "verbose_name_plural": "Tarefas de Integração Institucionais",
                "db_table": "tarefas_integracao_institucionais",
                "ordering": ["criado_em"],
            },
        ),
        migrations.AddField(
            model_name="candidaturainstitucional",
            name="vaga",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidaturas",
                to="users.vagainstitucional",
            ),
        ),
        migrations.CreateModel(
            name="NotaMetricaInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.PositiveSmallIntegerField(default=3)),
                (
                    "avaliacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_metricas",
                        to="users.avaliacaoinstitucional",
                    ),
                ),
                (
                    "metrica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.metricaavaliacaoinstitucional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Métrica Institucional",
                "verbose_name_plural": "Notas de Métricas Institucionais",
                "db_table": "notas_metricas_avaliacao_institucionais",
                "unique_together": {("avaliacao", "metrica")},
            },
        ),
        migrations.CreateModel(
            name="SubsidioReciboInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Aplicado"
                    ),
                ),
                (
                    "valor_padrao",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor Padrão Original",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "recibo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsidios_vinculados",
                        to="users.recibosalarialinstitucional",
                    ),
                ),
                (
                    "subsidio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.subsidioinstitucional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subsídio do Recibo Institucional",
                "verbose_name_plural": "Subsídios do Recibo Institucionais",
                "db_table": "recibo_subsidios_institucionais",
                "ordering": ["subsidio__codigo"],
                "unique_together": {("recibo", "subsidio")},
            },
        ),
    ]
