# Generated by Django 4.2.30 on 2026-06-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0023_alter_processamentosalarial_unique_together_and_more'),
        ('users', '0036_add_subperms_to_existing_cargos'),
    ]

    operations = [
        migrations.AddField(
            model_name='logatividade',
            name='banca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_atividade', to='rh.banca', verbose_name='Banca'),
        ),
        migrations.AddField(
            model_name='logatividade',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_atividade', to='rh.filialbanca', verbose_name='Filial'),
        ),
    ]
