# Generated by Django 4.2.30 on 2026-06-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_logatividade_banca_logatividade_filial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subsidioinstitucional',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subsidioinstitucional',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código Interno'),
        ),
        migrations.AddIndex(
            model_name='logatividade',
            index=models.Index(fields=['usuario', '-created_at'], name='idx_log_usuario_data'),
        ),
        migrations.AddIndex(
            model_name='logatividade',
            index=models.Index(fields=['modulo', '-created_at'], name='idx_log_modulo'),
        ),
    ]
