# Generated by Django 4.2.30 on 2026-06-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_subsidioinstitucional_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaturainstitucional',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='candidaturainstitucional',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='candidaturainstitucional',
            name='nome',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cicloavaliacaoinstitucional',
            name='periodo_inicio',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='colaboradorinstitucional',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='colaboradorinstitucional',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='colaboradorinstitucional',
            name='telefone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='entrevistainstitucional',
            name='data_hora',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='feriasinstitucional',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='metricaavaliacaoinstitucional',
            name='ordem',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='permissao',
            name='grupo',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Agrupamento visual (ex: Secretaria, Financeiro)', max_length=100),
        ),
        migrations.AlterField(
            model_name='planointegracaoinstitucional',
            name='estado',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Curso', 'Em Curso'), ('Concluído', 'Concluído')], db_index=True, default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='presencainstitucional',
            name='data',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='processamentosalarialinstitucional',
            name='ano',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='processamentosalarialinstitucional',
            name='mes',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='subsidioinstitucional',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='tarefaintegracaoinstitucional',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vagainstitucional',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vagainstitucional',
            name='titulo',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
