# Generated by Django 4.2.30 on 2026-07-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_candidaturainstitucional_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nif',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
    ]
