# Generated by Django 4.2.30 on 2026-07-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_add_db_index_nif'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='assinatura',
            field=models.TextField(blank=True, default='', verbose_name='Assinatura Digital (Base64 PNG)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='assinatura_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Assinatura'),
        ),
    ]
