# Generated by Django 4.2.30 on 2026-04-29 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestorFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('nome_gestor', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gestor_filial', to='rh.colaborador')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestores', to='rh.filialbanca')),
            ],
            options={
                'verbose_name': 'Gestor de Filial',
                'verbose_name_plural': 'Gestores de Filial',
                'db_table': 'rh_gestores_filial',
                'unique_together': {('colaborador', 'filial')},
            },
        ),
    ]
