# Generated by Django 4.2.30 on 2026-04-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_add_filial_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='usuario_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
