# Generated by Django 4.2.30 on 2026-04-30 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_add_usuario_id_to_colaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim_prevista', models.DateField(blank=True, null=True)),
                ('responsavel', models.CharField(blank=True, default='', max_length=255)),
                ('estado', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Curso', 'Em Curso'), ('Concluído', 'Concluído')], default='Pendente', max_length=10)),
                ('notas', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('candidatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano_integracao', to='rh.candidatura')),
            ],
            options={
                'db_table': 'rh_planos_integracao',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(choices=[('Assistente', 'Assistente de Despacho'), ('Administrativo', 'Administrativo'), ('Financeiro', 'Financeiro'), ('Gestor', 'Gestor'), ('Outro', 'Outro')], default='Assistente', max_length=30),
        ),
        migrations.CreateModel(
            name='TarefaIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, default='')),
                ('responsavel', models.CharField(blank=True, default='', max_length=255)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='rh.planointegracao')),
            ],
            options={
                'db_table': 'rh_tarefas_integracao',
                'ordering': ['prazo', 'criado_em'],
            },
        ),
        migrations.AddField(
            model_name='planointegracao',
            name='colaborador',
            field=models.ForeignKey(blank=True, help_text='Preenchido após criação do colaborador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plano_integracao', to='rh.colaborador'),
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('Presencial', 'Presencial'), ('Online', 'Online / Videochamada'), ('Telefonica', 'Telefónica')], default='Presencial', max_length=15)),
                ('local_link', models.CharField(blank=True, default='', max_length=300, verbose_name='Local / Link')),
                ('entrevistador', models.CharField(blank=True, default='', max_length=255)),
                ('resultado', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Reagendada', 'Reagendada')], default='Pendente', max_length=15)),
                ('nota', models.PositiveSmallIntegerField(blank=True, help_text='Nota de 1 a 10', null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('candidatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistas', to='rh.candidatura')),
            ],
            options={
                'db_table': 'rh_entrevistas',
                'ordering': ['data_hora'],
            },
        ),
    ]
