# Generated by Django 4.2.30 on 2026-04-30 12:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_planointegracao_alter_colaborador_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='link_externo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
