# Generated by Django 4.2.30 on 2026-04-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_add_link_externo_to_vaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='filialbanca',
            name='tem_responsavel',
            field=models.BooleanField(default=False, verbose_name='Deseja designar um responsável?'),
        ),
    ]
