# Generated by Django 4.2.30 on 2026-04-30 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0006_add_tem_responsavel_to_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registopresenca',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, help_text='Quem aprovou/rejeitou este registo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencas_aprovadas', to='rh.colaborador'),
        ),
        migrations.AddField(
            model_name='registopresenca',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registopresenca',
            name='tipo',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Saida', 'Saída'), ('Hora_Extra', 'Hora Extra'), ('Falta', 'Falta'), ('Falta_Justificada', 'Falta Justificada'), ('Ferias', 'Férias'), ('Feriado', 'Feriado')], default='Entrada', max_length=20),
        ),
    ]
