# Generated by Django 4.2.30 on 2026-04-30 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_update_presenca_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Subsídio')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código Interno')),
                ('tipo_calculo', models.CharField(choices=[('FIXO', 'Valor Fixo'), ('PERCENTUAL', 'Percentual do Salário'), ('DIAS_TRABALHO', 'Por Dias de Trabalho'), ('DEPENDENTES', 'Por Número de Dependentes')], default='FIXO', max_length=20)),
                ('valor_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Padrão')),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentual (%)')),
                ('ativo', models.BooleanField(default=True)),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='Obrigatório para Todos')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidios', to='rh.banca')),
            ],
            options={
                'verbose_name': 'Subsídio',
                'verbose_name_plural': 'Subsídios',
                'db_table': 'rh_subsidios',
                'ordering': ['codigo'],
                'unique_together': {('banca', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('SALARIO_DESPACHANTE', 'Pagamento de Salário - Despachante'), ('SALARIO_COLABORADOR', 'Pagamento de Salário - Colaborador')], max_length=25)),
                ('estado', models.CharField(choices=[('EMITIDA', 'Emitida'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='EMITIDA', max_length=15)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_imposto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_por', models.IntegerField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='rh.banca')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='rh.colaborador')),
                ('processamento_salarial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='rh.processamentosalarial')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'db_table': 'rh_faturas',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CV', 'Curriculum Vitae'), ('DECLARACAO', 'Declaração'), ('CERTIFICADO', 'Certificado'), ('OUTRO', 'Outro Documento')], default='OUTRO', max_length=20)),
                ('arquivo', models.FileField(upload_to='colaboradores/documentos/%Y/%m/')),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='rh.colaborador')),
            ],
            options={
                'verbose_name': 'Documento do Colaborador',
                'verbose_name_plural': 'Documentos dos Colaboradores',
                'db_table': 'rh_colaborador_documentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SubsidioRecibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Aplicado')),
                ('valor_padrao', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Padrão Original')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidios_vinculados', to='rh.recibosalarial')),
                ('subsidio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.subsidio')),
            ],
            options={
                'verbose_name': 'Subsídio do Recibo',
                'verbose_name_plural': 'Subsídios do Recibo',
                'db_table': 'rh_recibo_subsidios',
                'ordering': ['subsidio__codigo'],
                'unique_together': {('recibo', 'subsidio')},
            },
        ),
    ]
