# Generated by Django 4.2.30 on 2026-04-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0008_subsidio_fatura_documentocolaborador_subsidiorecibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='processamentosalarial',
            name='pdf_gerado',
            field=models.BooleanField(default=False),
        ),
    ]
