# Generated by Django 4.2.30 on 2026-05-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0009_processamentosalarial_pdf_gerado'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='password',
            field=models.CharField(blank=True, help_text='Senha para acesso ao sistema', max_length=255, null=True),
        ),
    ]
