# Generated by Django 5.2 on 2026-05-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0010_add_password_to_colaborador"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="banca",
            index=models.Index(
                fields=["usuario_id"], name="rh_empresas_usuario_8a2f5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banca",
            index=models.Index(fields=["ativa"], name="rh_empresas_ativa_119907_idx"),
        ),
        migrations.AddIndex(
            model_name="banca",
            index=models.Index(fields=["nif"], name="rh_empresas_nif_f3dd04_idx"),
        ),
        migrations.AddIndex(
            model_name="candidatura",
            index=models.Index(fields=["vaga"], name="rh_candidat_vaga_id_c9c0d6_idx"),
        ),
        migrations.AddIndex(
            model_name="candidatura",
            index=models.Index(fields=["estado"], name="rh_candidat_estado_810cc6_idx"),
        ),
        migrations.AddIndex(
            model_name="candidatura",
            index=models.Index(
                fields=["vaga", "estado"], name="rh_candidat_vaga_id_f0a429_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidatura",
            index=models.Index(
                fields=["criado_em"], name="rh_candidat_criado__479960_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="colaborador",
            index=models.Index(fields=["banca"], name="rh_colabora_banca_i_4d583d_idx"),
        ),
        migrations.AddIndex(
            model_name="colaborador",
            index=models.Index(
                fields=["filial"], name="rh_colabora_filial__8dfc92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="colaborador",
            index=models.Index(fields=["estado"], name="rh_colabora_estado_fc2622_idx"),
        ),
        migrations.AddIndex(
            model_name="colaborador",
            index=models.Index(
                fields=["usuario_id"], name="rh_colabora_usuario_97bc52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="colaborador",
            index=models.Index(
                fields=["banca", "filial"], name="rh_colabora_banca_i_2ac326_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="colaborador",
            index=models.Index(
                fields=["criado_em"], name="rh_colabora_criado__a010c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="filialbanca",
            index=models.Index(
                fields=["banca", "ativa"], name="rh_filiais_banca_i_77607a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="filialbanca",
            index=models.Index(
                fields=["provincia"], name="rh_filiais_provinc_521b1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gestorfilial",
            index=models.Index(
                fields=["colaborador", "ativo"], name="rh_gestores_colabor_aa6dbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gestorfilial",
            index=models.Index(
                fields=["filial", "ativo"], name="rh_gestores_filial__b72f52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vaga",
            index=models.Index(fields=["banca"], name="rh_vagas_banca_i_fba620_idx"),
        ),
        migrations.AddIndex(
            model_name="vaga",
            index=models.Index(fields=["filial"], name="rh_vagas_filial__9dd631_idx"),
        ),
        migrations.AddIndex(
            model_name="vaga",
            index=models.Index(fields=["estado"], name="rh_vagas_estado_243e15_idx"),
        ),
        migrations.AddIndex(
            model_name="vaga",
            index=models.Index(
                fields=["banca", "estado"], name="rh_vagas_banca_i_67f9f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vaga",
            index=models.Index(
                fields=["criado_em"], name="rh_vagas_criado__dd04ee_idx"
            ),
        ),
    ]
