# Generated by Django 5.2 on 2026-06-02 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0013_remove_banca_idx_banca_criado_em_and_more"),
        ("users", "0005_add_secretario_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CargoMesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "funcao",
                    models.CharField(
                        choices=[
                            ("Presidente", "Presidente"),
                            ("Vice-Presidente", "Vice-Presidente"),
                            ("1º Secretário", "1º Secretário"),
                            ("2º Secretário", "2º Secretário"),
                            ("Secretário", "Secretário"),
                            ("Vogal", "Vogal"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("atribuido_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargo_mesa",
                        to="users.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo da Mesa",
                "verbose_name_plural": "Cargos da Mesa",
                "db_table": "rh_cargos_mesa",
            },
        ),
    ]
