# Generated by Django 5.2 on 2026-06-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0015_subsidio_especificos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subsidio",
            name="apenas_especificos",
            field=models.BooleanField(
                default=False,
                help_text="Se marcado, este subsídio só é aplicado aos colaboradores selecionados abaixo.",
                verbose_name="Apenas para colaboradores específicos",
            ),
        ),
    ]
