# Generated by Django 5.2 on 2026-06-03 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0016_alter_subsidio_apenas_especificos"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricaAvaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(blank=True, default="", max_length=255)),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metricas",
                        to="rh.cicloavaliacao",
                    ),
                ),
            ],
            options={
                "db_table": "rh_metricas_avaliacao",
                "ordering": ["ordem"],
                "unique_together": {("ciclo", "nome")},
            },
        ),
        migrations.CreateModel(
            name="NotaMetrica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.PositiveSmallIntegerField(default=3)),
                (
                    "avaliacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_metricas",
                        to="rh.avaliacao",
                    ),
                ),
                (
                    "metrica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="rh.metricaavaliacao",
                    ),
                ),
            ],
            options={
                "db_table": "rh_notas_metricas",
                "unique_together": {("avaliacao", "metrica")},
            },
        ),
    ]
