# Generated by Django 5.2 on 2026-06-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0017_metricaavaliacao_notametrica"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banca",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, default="", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="banca",
            name="nome",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="candidatura",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="candidatura",
            name="nome",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, default="", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="nome",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
