# Generated by Django 5.2 on 2026-06-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0018_add_nome_email_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrevista",
            name="resultado",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aprovado", "Aprovado"),
                    ("Reprovado", "Reprovado"),
                    ("Reagendada", "Reagendada"),
                ],
                db_index=True,
                default="Pendente",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="fatura",
            name="data_emissao",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="fatura",
            name="estado",
            field=models.CharField(
                choices=[
                    ("EMITIDA", "Emitida"),
                    ("PAGA", "Paga"),
                    ("CANCELADA", "Cancelada"),
                ],
                db_index=True,
                default="EMITIDA",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="fatura",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("SALARIO_DESPACHANTE", "Pagamento de Salário - Despachante"),
                    ("SALARIO_COLABORADOR", "Pagamento de Salário - Colaborador"),
                ],
                db_index=True,
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="pedidoferias",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aprovado", "Aprovado"),
                    ("Rejeitado", "Rejeitado"),
                ],
                db_index=True,
                default="Pendente",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="planointegracao",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Em Curso", "Em Curso"),
                    ("Concluído", "Concluído"),
                ],
                db_index=True,
                default="Pendente",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="registopresenca",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aprovado", "Aprovado"),
                    ("Rejeitado", "Rejeitado"),
                ],
                db_index=True,
                default="Pendente",
                max_length=10,
            ),
        ),
    ]
