# Generated by Django 5.2 on 2026-06-12 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0019_add_db_index_to_query_fields"),
        ("users", "0029_add_db_index_to_query_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CargoBanca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "banca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargos",
                        to="rh.banca",
                    ),
                ),
                (
                    "permissoes",
                    models.ManyToManyField(
                        blank=True, related_name="cargos_banca", to="users.permissao"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo da Banca",
                "verbose_name_plural": "Cargos da Banca",
                "db_table": "rh_cargos_banca",
                "ordering": ["nome"],
                "unique_together": {("banca", "nome")},
            },
        ),
        migrations.AddField(
            model_name="colaborador",
            name="cargo_banca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="colaboradores",
                to="rh.cargobanca",
            ),
        ),
    ]
