# Generated by Django 4.2.30 on 2026-06-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0021_seed_permissoes_cargos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargobanca',
            name='locked',
            field=models.BooleanField(default=False, help_text='Se marcado, as permissões não podem ser alteradas manualmente (controladas pelo sistema)', verbose_name='Bloqueado'),
        ),
    ]
