# Generated by Django 4.2.30 on 2026-06-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0022_multi_tenant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='processamentosalarial',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fatura',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas', to='rh.filialbanca'),
        ),
        migrations.AddField(
            model_name='processamentosalarial',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processamentos', to='rh.filialbanca'),
        ),
        migrations.AlterUniqueTogether(
            name='processamentosalarial',
            unique_together={('banca', 'filial', 'mes', 'ano')},
        ),
    ]
