# Generated by Django 4.2.30 on 2026-06-24 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0029_remove_gerir_governanca_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoferias',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ferias_aprovadas', to='rh.colaborador'),
        ),
        migrations.AddField(
            model_name='pedidoferias',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NotificacaoRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aprovacao_pendente', 'Aprovação Pendente'), ('pedido_aprovado', 'Pedido Aprovado'), ('pedido_rejeitado', 'Pedido Rejeitado'), ('delegacao_recebida', 'Delegação Recebida'), ('delegacao_expirada', 'Delegação Expirada'), ('sla_alerta', 'Alerta SLA')], max_length=30)),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_rh', to='rh.banca')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_rh', to='rh.colaborador')),
            ],
            options={
                'db_table': 'rh_notificacoes',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['destinatario', 'lida'], name='rh_notifica_destina_b71fa5_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_registo', models.CharField(choices=[('presenca', 'Presença'), ('ferias', 'Férias')], max_length=20)),
                ('registo_id', models.PositiveIntegerField()),
                ('accao', models.CharField(choices=[('CRIADA', 'Criada'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('ALTERADA', 'Alterada'), ('REMOVIDA', 'Removida'), ('FALTA_AUTO', 'Falta Auto-Marcada')], max_length=20)),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=20)),
                ('estado_novo', models.CharField(blank=True, default='', max_length=20)),
                ('colaborador_nome', models.CharField(blank=True, default='', max_length=255)),
                ('aprovador_nome', models.CharField(blank=True, default='', max_length=255)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rh.colaborador')),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_presencas', to='rh.banca')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rh.colaborador')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.filialbanca')),
            ],
            options={
                'db_table': 'rh_historico_presencas',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['banca', 'tipo_registo', 'registo_id'], name='rh_historic_banca_i_900a8d_idx'), models.Index(fields=['colaborador'], name='rh_historic_colabor_e47a5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DelegacaoAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('motivo', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegacoes_aprovacao', to='rh.banca')),
                ('delegado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegacoes_recebidas', to='rh.colaborador')),
                ('delegante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegacoes_feitas', to='rh.colaborador')),
            ],
            options={
                'db_table': 'rh_delegacoes_aprovacao',
                'indexes': [models.Index(fields=['delegante', 'ativo'], name='rh_delegaco_delegan_db3b2f_idx'), models.Index(fields=['delegado', 'ativo'], name='rh_delegaco_delegad_5ef642_idx')],
            },
        ),
    ]
