# Generated by Django 4.2.30 on 2026-06-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0030_fluxo_aprovacao_profissional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargobanca',
            name='nome',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cicloavaliacao',
            name='periodo_inicio',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='bi',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Nº BI'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(choices=[('Assistente', 'Assistente de Despacho'), ('Administrativo', 'Administrativo'), ('Financeiro', 'Financeiro'), ('Gestor', 'Gestor'), ('Outro', 'Outro')], db_index=True, default='Assistente', max_length=30),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='data_admissao',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='departamento',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nif',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='documentocolaborador',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='data_hora',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='criado_por',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='data_vencimento',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicopresenca',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='metricaavaliacao',
            name='ordem',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='notificacaorh',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pedidoferias',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='planointegracao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='processamentosalarial',
            name='ano',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='processamentosalarial',
            name='mes',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='registopresenca',
            name='data',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='subsidio',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='subsidio',
            name='codigo',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Código Interno'),
        ),
        migrations.AlterField(
            model_name='tarefaintegracao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tarefaintegracao',
            name='prazo',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
