# Generated by Django 4.2.30 on 2026-07-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0031_alter_cargobanca_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='banco',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='num_conta',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nº de Conta'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='titular_conta',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Titular da Conta'),
        ),
    ]
