# Generated by Django 4.2.30 on 2026-07-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0032_adicionar_campos_bancarios_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='banca',
            name='bai',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='BAI'),
        ),
        migrations.AddField(
            model_name='banca',
            name='banco',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='banca',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='banca',
            name='instrucoes_pagamento',
            field=models.TextField(blank=True, default='', verbose_name='Instruções de Pagamento'),
        ),
        migrations.AddField(
            model_name='banca',
            name='numero_conta',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nº da Conta'),
        ),
        migrations.AlterField(
            model_name='banca',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='bancas/logos/', verbose_name='Logotipo'),
        ),
    ]
