# Generated by Django 4.2.30 on 2026-07-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0033_adicionar_campos_bancarios_banca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banca',
            name='bai',
        ),
    ]
