# Generated by Django 4.2.30 on 2026-07-11 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0035_add_dados_bancarios_json_banca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='rh.colaborador'),
        ),
        migrations.AlterField(
            model_name='recibosalarial',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='rh.colaborador'),
        ),
    ]
