# Generated by Django 4.2.30 on 2026-07-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_delete_aprovar_requisicao'),
        ('rh', '0036_alter_avaliacao_colaborador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='permissoes_filiais',
            field=models.ManyToManyField(blank=True, related_name='colaboradores_filiais', to='users.permissao', verbose_name='Permissões de Filial (atribuídas pelo gestor)'),
        ),
    ]
