# Generated by Django 4.2.30 on 2026-07-14 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0037_add_permissoes_filiais_to_colaborador'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cargobanca',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cargobanca',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Se definido, este cargo é específico desta filial.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='rh.filialbanca', verbose_name='Filial'),
        ),
        migrations.AlterUniqueTogether(
            name='cargobanca',
            unique_together={('banca', 'filial', 'nome')},
        ),
    ]
