# Generated by Django 4.2.30 on 2026-07-14 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0038_add_filial_to_cargobanca'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('dias_direito', models.PositiveIntegerField(default=22)),
                ('dias_gozados', models.PositiveIntegerField(default=0)),
                ('dias_pendentes', models.PositiveIntegerField(default=0)),
                ('transferido_anterior', models.PositiveIntegerField(default=0, verbose_name='Dias transferidos do ano anterior')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_ferias', to='rh.colaborador')),
            ],
            options={
                'db_table': 'rh_saldos_ferias',
                'ordering': ['-ano'],
                'unique_together': {('colaborador', 'ano')},
            },
        ),
    ]
