# Generated by Django 4.2.30 on 2026-07-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0039_saldoferias'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoferias',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, default='', verbose_name='Motivo da rejeição'),
        ),
    ]
