# Generated by Django 4.2.30 on 2026-07-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0040_add_motivo_rejeicao_to_pedidoferias'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancaCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=255)),
                ('nif', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('Singular', 'Empresa em Nome Individual'), ('Sociedade', 'Sociedade por Quotas'), ('SA', 'Sociedade Anónima'), ('Outro', 'Outro')], default='SA', max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('telefone', models.CharField(blank=True, default='', max_length=30)),
                ('endereco', models.TextField(blank=True, default='')),
                ('provincia', models.CharField(blank=True, default='', max_length=100)),
                ('municipio', models.CharField(blank=True, default='', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='banca_central/logos/')),
                ('banco', models.CharField(blank=True, default='', max_length=255)),
                ('numero_conta', models.CharField(blank=True, default='', max_length=50)),
                ('iban', models.CharField(blank=True, default='', max_length=50)),
                ('dados_bancarios_json', models.TextField(blank=True, default='[]')),
                ('instrucoes_pagamento', models.TextField(blank=True, default='')),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banca Central',
                'verbose_name_plural': 'Bancas Centrais',
                'db_table': 'rh_banca_central',
            },
        ),
    ]
