# Generated by Django 4.2.30 on 2026-07-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0041_bancacentral'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancacentral',
            name='assinatura',
            field=models.ImageField(blank=True, help_text='Assinatura digital do responsável (imagem PNG com fundo transparente)', null=True, upload_to='banca_central/assinaturas/'),
        ),
    ]
