# Generated by Django 5.2 on 2026-05-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeclaracaoUnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_du",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("processo_id", models.IntegerField(blank=True, null=True)),
                (
                    "nif_declarante",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "nome_declarante",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("endereco_declarante", models.TextField(blank=True, null=True)),
                (
                    "regime_aduaneiro",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "codigo_pautal",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("descricao_mercadoria", models.TextField(blank=True, null=True)),
                ("quantidade", models.IntegerField(default=0)),
                (
                    "peso_bruto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "peso_liquido",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "valor_fob",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "valor_frete",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, null=True
                    ),
                ),
                (
                    "valor_seguro",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, null=True
                    ),
                ),
                (
                    "valor_cif",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "direitos_aduaneiros",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, null=True
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, null=True
                    ),
                ),
                (
                    "imposto_consumo",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, null=True
                    ),
                ),
                (
                    "emolumentos",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, null=True
                    ),
                ),
                (
                    "total_impostos",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, null=True
                    ),
                ),
                (
                    "pais_origem",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "porto_embarque",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "porto_desembarque",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "meio_transporte",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Rascunho", "Rascunho"),
                            ("Submetida", "Submetida"),
                            ("Em Análise", "Em Análise"),
                            ("Aprovada", "Aprovada"),
                            ("Rejeitada", "Rejeitada"),
                        ],
                        default="Rascunho",
                        max_length=20,
                    ),
                ),
                ("data_submissao", models.DateTimeField(blank=True, null=True)),
                ("data_aprovacao", models.DateTimeField(blank=True, null=True)),
                ("usuario_id", models.IntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "du_uuid",
                    models.CharField(
                        blank=True, db_column="du_uuid", default="", max_length=36
                    ),
                ),
                (
                    "codigo_processo",
                    models.CharField(blank=True, max_length=8, null=True, unique=True),
                ),
                (
                    "ref_despachante",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "exportador_nome",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "destinatario_nome",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "total_derimp",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_iec",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_emgead",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_direxp",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_iva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_geral",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("dados_json", models.TextField(default="{}")),
            ],
            options={
                "verbose_name": "Declaração Única",
                "verbose_name_plural": "Declarações Únicas",
                "db_table": "declaracoes_unicas",
                "ordering": ["-created_at"],
                "managed": True,
            },
        ),
    ]
