# Generated by Django 5.2 on 2026-05-31 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aduaneiro", "0002_add_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="declaracaounica",
            name="idx_du_status",
        ),
        migrations.RemoveIndex(
            model_name="declaracaounica",
            name="idx_du_created_at",
        ),
        migrations.RemoveIndex(
            model_name="declaracaounica",
            name="idx_du_usuario_status",
        ),
        migrations.RemoveIndex(
            model_name="declaracaounica",
            name="idx_du_usuario_created",
        ),
    ]
