# Generated by Django 5.2 on 2026-06-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aduaneiro", "0003_remove_declaracaounica_idx_du_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="declaracaounica",
            name="status",
            field=models.CharField(
                choices=[
                    ("Rascunho", "Rascunho"),
                    ("Submetida", "Submetida"),
                    ("Em Análise", "Em Análise"),
                    ("Aprovada", "Aprovada"),
                    ("Rejeitada", "Rejeitada"),
                ],
                db_index=True,
                default="Rascunho",
                max_length=20,
            ),
        ),
    ]
