# Generated by Django 5.2 on 2026-06-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aduaneiro", "0004_alter_declaracaounica_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="declaracaounica",
            name="du_uuid",
            field=models.CharField(
                blank=True,
                db_column="du_uuid",
                db_index=True,
                default="",
                max_length=36,
            ),
        ),
    ]
