# Generated by Django 5.2 on 2026-06-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aduaneiro", "0005_add_du_uuid_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="declaracaounica",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="declaracaounica",
            name="data_submissao",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
