# Generated by Django 5.2 on 2026-06-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aduaneiro", "0006_add_db_index_to_query_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="declaracaounica",
            index=models.Index(
                fields=["status", "-created_at"], name="ix_du_status_data"
            ),
        ),
        migrations.AddIndex(
            model_name="declaracaounica",
            index=models.Index(
                fields=["usuario_id", "-created_at"], name="ix_du_usuario_data"
            ),
        ),
    ]
