# Generated by Django 4.2.30 on 2026-06-23 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0022_multi_tenant'),
        ('aduaneiro', '0007_add_composite_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracaounica',
            name='banca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='declaracoes', to='rh.banca'),
        ),
        migrations.AddField(
            model_name='declaracaounica',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declaracoes', to='rh.filialbanca'),
        ),
    ]
