# Generated by Django 4.2.30 on 2026-06-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduaneiro', '0008_multi_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracaounica',
            name='codigo_processo',
            field=models.CharField(blank=True, default='', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='declaracaounica',
            name='direitos_aduaneiros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='declaracaounica',
            name='emolumentos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='declaracaounica',
            name='imposto_consumo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='declaracaounica',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='declaracaounica',
            name='numero_du',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='declaracaounica',
            name='total_impostos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='declaracaounica',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='declaracaounica',
            name='valor_seguro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
