# Generated by Django 4.2.30 on 2026-06-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduaneiro', '0009_alter_declaracaounica_codigo_processo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracaounica',
            name='codigo_pautal',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='declaracaounica',
            name='nif_declarante',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='declaracaounica',
            name='nome_declarante',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='declaracaounica',
            name='pais_origem',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaounica',
            name='processo_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaounica',
            name='regime_aduaneiro',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
