# Generated by Django 4.2.30 on 2026-06-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduaneiro', '0010_alter_declaracaounica_codigo_pautal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracaounica',
            name='numero_du',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True),
        ),
    ]
