# Generated by Django 4.2.30 on 2026-06-28 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aduaneiro', '0011_corrige_numero_du_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoDU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_json', models.TextField(verbose_name='Dados Completos (snapshot)')),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='Estado')),
                ('numero_du', models.CharField(blank=True, default='', max_length=50, verbose_name='Número DU')),
                ('codigo_processo', models.CharField(blank=True, default='', max_length=8, verbose_name='Código Processo')),
                ('campos_alterados', models.TextField(blank=True, default='', verbose_name='Campos Alterados (JSON)')),
                ('utilizador_id', models.IntegerField(blank=True, null=True, verbose_name='ID do Utilizador')),
                ('utilizador_nome', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome do Utilizador')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora')),
                ('du', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_versoes', to='aduaneiro.declaracaounica')),
            ],
            options={
                'verbose_name': 'Histórico de DU',
                'verbose_name_plural': 'Históricos de DU',
                'db_table': 'aduaneiro_historico_du',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['du', '-criado_em'], name='ix_historico_du_data')],
            },
        ),
    ]
