# Generated by Django 4.2.30 on 2026-07-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduaneiro', '0012_historicodu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracaounica',
            name='destinatario_nome',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='declaracaounica',
            name='exportador_nome',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='declaracaounica',
            name='ref_despachante',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
