# Generated by Django 4.2.30 on 2026-07-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduaneiro', '0013_add_db_index_search_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracaounica',
            name='status',
            field=models.CharField(choices=[('Rascunho', 'Rascunho'), ('Submetida', 'Submetida'), ('Em Análise', 'Em Análise'), ('Aprovada', 'Aprovada'), ('Rejeitada', 'Rejeitada'), ('Finalizada', 'Finalizada')], db_index=True, default='Rascunho', max_length=20),
        ),
    ]
