# Generated by Django 4.2.30 on 2026-07-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduaneiro', '0014_adicionar_status_finalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracaounica',
            name='nome_banco',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='declaracaounica',
            name='termo_pagamento',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
