# Generated by Django 4.2.30 on 2026-07-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduaneiro', '0015_add_nome_banco_termo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracaounica',
            name='regime_aduaneiro',
            field=models.CharField(blank=True, choices=[('IM4', 'IM4 - Importação definitiva'), ('IM5', 'IM5 - Importação temporária'), ('IM6', 'IM6 - Reimportação'), ('IM7', 'IM7 - Armazenagem'), ('IM8', 'IM8 - Trânsito e Transbordo'), ('IMS4', 'IMS4 - Importação definitiva simplificada'), ('IMS5', 'IMS5 - Importação temporária simplificada'), ('IMS6', 'IMS6 - Reimportação simplificada'), ('IMS7', 'IMS7 - Armazenagem simplificada'), ('IMS8', 'IMS8 - Trânsito e Transbordo simplificado'), ('IMV4', 'IMV4 - Importação definitiva verbal'), ('IMV5', 'IMV5 - Importação temporária verbal'), ('IMV6', 'IMV6 - Reimportação verbal'), ('IMV7', 'IMV7 - Armazenagem verbal'), ('IMV8', 'IMV8 - Trânsito e Transbordo verbal'), ('EX1', 'EX1 - Exportação definitiva'), ('EX2', 'EX2 - Exportação temporária'), ('EX3', 'EX3 - Reexportação'), ('EXS1', 'EXS1 - Exportação definitiva simplificada'), ('EXS2', 'EXS2 - Exportação temporária simplificada'), ('EXS3', 'EXS3 - Reexportação simplificada'), ('EXV1', 'EXV1 - Exportação definitiva verbal'), ('EXV2', 'EXV2 - Exportação temporária verbal'), ('EXV3', 'EXV3 - Reexportação verbal')], db_index=True, default='', max_length=100),
        ),
    ]
