# Generated by Django 5.2 on 2026-05-29 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assembleia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("descricao", models.TextField(blank=True, default="")),
                ("data_hora", models.DateTimeField()),
                ("data_encerramento", models.DateTimeField(blank=True, null=True)),
                (
                    "local",
                    models.CharField(
                        blank=True, default="Sala Virtual CDOA", max_length=300
                    ),
                ),
                (
                    "link_streaming",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "livekit_room",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Agendada", "Agendada"),
                            ("Em Curso", "Em Curso"),
                            ("Concluida", "Concluída"),
                            ("Cancelada", "Cancelada"),
                        ],
                        default="Agendada",
                        max_length=20,
                    ),
                ),
                (
                    "quorum_minimo",
                    models.IntegerField(
                        default=0, help_text="Número mínimo de presentes para quórum"
                    ),
                ),
                (
                    "total_eleitores",
                    models.IntegerField(
                        default=0, help_text="Total de despachantes com direito a voto"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hash_integridade",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assembleia",
                "verbose_name_plural": "Assembleias",
                "db_table": "governanca_assembleias",
                "ordering": ["-data_hora"],
            },
        ),
        migrations.CreateModel(
            name="AtaDigital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conteudo", models.TextField()),
                (
                    "assinatura_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("assinado_em", models.DateTimeField(blank=True, null=True)),
                ("publicado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "arquivo_pdf",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assembleia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atas",
                        to="governanca.assembleia",
                    ),
                ),
                (
                    "assinado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atas_assinadas",
                        to="users.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ata Digital",
                "verbose_name_plural": "Atas Digitais",
                "db_table": "governanca_atas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ManifestoIntegridade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash_consolidado", models.CharField(max_length=64)),
                ("dados_json", models.TextField(default="{}")),
                ("gerado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "assembleia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manifestos",
                        to="governanca.assembleia",
                    ),
                ),
                (
                    "gerado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manifesto de Integridade",
                "verbose_name_plural": "Manifestos de Integridade",
                "db_table": "governanca_manifestos",
            },
        ),
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("assembleia_agendada", "Assembleia Agendada"),
                            ("assembleia_iniciada", "Assembleia Iniciada"),
                            ("votacao_aberta", "Votação Aberta"),
                            ("procuracao_solicitada", "Procuração Solicitada"),
                            ("procuracao_confirmada", "Procuração Confirmada"),
                            ("resultado_publicado", "Resultado Publicado"),
                            ("ata_publicada", "Ata Publicada"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("mensagem", models.TextField(blank=True, default="")),
                ("link", models.CharField(blank=True, default="", max_length=500)),
                ("lida", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to="users.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "db_table": "governanca_notificacoes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PautaVotacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("descricao", models.TextField(blank=True, default="")),
                ("ordem", models.IntegerField(default=0)),
                (
                    "tipo_votacao",
                    models.CharField(
                        choices=[("Aberta", "Aberta"), ("Secreta", "Secreta")],
                        default="Aberta",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Em Votacao", "Em Votacao"),
                            ("Concluida", "Concluida"),
                        ],
                        default="Pendente",
                        max_length=20,
                    ),
                ),
                (
                    "resultado_final",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("iniciado_em", models.DateTimeField(blank=True, null=True)),
                ("encerrado_em", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assembleia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pautas",
                        to="governanca.assembleia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pauta de Votação",
                "verbose_name_plural": "Pautas de Votação",
                "db_table": "governanca_pautas",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="PresencaAssembleia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("presente_em", models.DateTimeField(blank=True, null=True)),
                ("saiu_em", models.DateTimeField(blank=True, null=True)),
                ("ip_registro", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "assembleia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presencas",
                        to="governanca.assembleia",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.usuario"
                    ),
                ),
            ],
            options={
                "verbose_name": "Presença",
                "verbose_name_plural": "Presenças",
                "db_table": "governanca_presencas",
                "unique_together": {("assembleia", "usuario")},
            },
        ),
        migrations.CreateModel(
            name="Procuracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_otp", models.CharField(blank=True, default="", max_length=6)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Confirmada", "Confirmada"),
                            ("Cancelada", "Cancelada"),
                        ],
                        default="Pendente",
                        max_length=20,
                    ),
                ),
                ("confirmado_em", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assembleia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procuracao",
                        to="governanca.assembleia",
                    ),
                ),
                (
                    "outorgado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procuracao_outorgado",
                        to="users.usuario",
                    ),
                ),
                (
                    "outorgante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procuracao_outorgante",
                        to="users.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procuração",
                "verbose_name_plural": "Procurações",
                "db_table": "governanca_procuracao",
                "unique_together": {("assembleia", "outorgante")},
            },
        ),
        migrations.CreateModel(
            name="Voto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opcao",
                    models.CharField(
                        choices=[
                            ("Favor", "A Favor"),
                            ("Contra", "Contra"),
                            ("Abstencao", "Abstenção"),
                        ],
                        max_length=20,
                    ),
                ),
                ("em_delegacao", models.BooleanField(default=False)),
                (
                    "hash_auditoria",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("votado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "delegado_de",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="votos_delegados",
                        to="users.usuario",
                    ),
                ),
                (
                    "pauta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votos",
                        to="governanca.pautavotacao",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.usuario"
                    ),
                ),
            ],
            options={
                "verbose_name": "Voto",
                "verbose_name_plural": "Votos",
                "db_table": "governanca_votos",
                "unique_together": {("pauta", "usuario", "em_delegacao")},
            },
        ),
    ]
