# Generated by Django 5.2 on 2026-05-29 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanca", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voto",
            name="opcao_encriptada",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="voto",
            name="recibo_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="ReciboVoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recibo_hash", models.CharField(max_length=64, unique=True)),
                ("pauta_titulo", models.CharField(max_length=300)),
                ("data_voto", models.DateTimeField()),
                ("verificado", models.BooleanField(default=False)),
                (
                    "voto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recibo",
                        to="governanca.voto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recibo de Voto",
                "verbose_name_plural": "Recibos de Voto",
                "db_table": "governanca_recibos_voto",
            },
        ),
    ]
