# Generated by Django 5.2 on 2026-05-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanca", "0002_voto_opcao_encriptada_voto_recibo_hash_recibovoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procuracao",
            name="codigo_otp",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
