# Generated by Django 5.2 on 2026-05-29 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanca", "0003_alter_procuracao_codigo_otp"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoAssembleia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ata", "Ata"),
                            ("relatorio", "Relatório"),
                            ("outro", "Outro"),
                        ],
                        default="ata",
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("descricao", models.TextField(blank=True, default="")),
                (
                    "arquivo",
                    models.FileField(
                        max_length=500, upload_to="documentos_assembleia/%Y/%m/"
                    ),
                ),
                ("publicado", models.BooleanField(default=False)),
                ("publicado_em", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assembleia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="governanca.assembleia",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "db_table": "governanca_documentos",
                "ordering": ["-created_at"],
            },
        ),
    ]
