# Generated by Django 5.2 on 2026-05-29 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanca", "0004_documentoassembleia"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembroMesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "funcao",
                    models.CharField(
                        choices=[
                            ("Presidente", "Presidente"),
                            ("Vice-Presidente", "Vice-Presidente"),
                            ("1º Secretário", "1º Secretário"),
                            ("2º Secretário", "2º Secretário"),
                            ("Secretário", "Secretário"),
                            ("Vogal", "Vogal"),
                        ],
                        max_length=30,
                    ),
                ),
                ("ordem", models.IntegerField(default=0)),
                (
                    "assembleia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesa",
                        to="governanca.assembleia",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.usuario"
                    ),
                ),
            ],
            options={
                "verbose_name": "Membro da Mesa",
                "verbose_name_plural": "Membros da Mesa",
                "db_table": "governanca_mesa",
                "ordering": ["ordem"],
                "unique_together": {("assembleia", "usuario")},
            },
        ),
    ]
