# Generated by Django 5.2 on 2026-05-29 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanca", "0005_membromesa"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MensagemChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("texto", "Texto"), ("reacao", "Reação")],
                        default="texto",
                        max_length=10,
                    ),
                ),
                ("texto", models.TextField(blank=True, default="")),
                (
                    "reacao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mao", "Mão 🖐️"),
                            ("palmas", "Palmas 👏"),
                            ("coracao", "Coração ❤️"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assembleia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens_chat",
                        to="governanca.assembleia",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.usuario"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem de Chat",
                "verbose_name_plural": "Mensagens de Chat",
                "db_table": "governanca_chat",
                "ordering": ["created_at"],
            },
        ),
    ]
