# Generated by Django 5.2 on 2026-05-30 21:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanca", "0006_mensagemchat"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificacao",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "NotificaÃ§Ã£o",
                "verbose_name_plural": "NotificaÃ§Ãµes",
            },
        ),
        migrations.AlterModelOptions(
            name="pautavotacao",
            options={
                "ordering": ["ordem"],
                "verbose_name": "Pauta de VotaÃ§Ã£o",
                "verbose_name_plural": "Pautas de VotaÃ§Ã£o",
            },
        ),
        migrations.AlterModelOptions(
            name="presencaassembleia",
            options={"verbose_name": "PresenÃ§a", "verbose_name_plural": "PresenÃ§as"},
        ),
        migrations.AlterModelOptions(
            name="procuracao",
            options={
                "verbose_name": "ProcuraÃ§Ã£o",
                "verbose_name_plural": "ProcuraÃ§Ãµes",
            },
        ),
        migrations.AlterField(
            model_name="assembleia",
            name="quorum_minimo",
            field=models.IntegerField(
                default=0, help_text="NÃºmero mÃ\xadnimo de presentes para quÃ³rum"
            ),
        ),
        migrations.AlterField(
            model_name="assembleia",
            name="status",
            field=models.CharField(
                choices=[
                    ("Agendada", "Agendada"),
                    ("Em Curso", "Em Curso"),
                    ("Concluida", "ConcluÃ\xadda"),
                    ("Cancelada", "Cancelada"),
                ],
                default="Agendada",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documentoassembleia",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ata", "Ata"),
                    ("relatorio", "RelatÃ³rio"),
                    ("outro", "Outro"),
                ],
                default="ata",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="membromesa",
            name="funcao",
            field=models.CharField(
                choices=[
                    ("Presidente", "Presidente"),
                    ("Vice-Presidente", "Vice-Presidente"),
                    ("1Âº SecretÃ¡rio", "1Âº SecretÃ¡rio"),
                    ("2Âº SecretÃ¡rio", "2Âº SecretÃ¡rio"),
                    ("SecretÃ¡rio", "SecretÃ¡rio"),
                    ("Vogal", "Vogal"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="mensagemchat",
            name="reacao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mao", "MÃ£o ðŸ–\x90ï¸\x8f"),
                    ("palmas", "Palmas ðŸ‘\x8f"),
                    ("coracao", "CoraÃ§Ã£o â\x9d¤ï¸\x8f"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="mensagemchat",
            name="tipo",
            field=models.CharField(
                choices=[("texto", "Texto"), ("reacao", "ReaÃ§Ã£o")],
                default="texto",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notificacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("assembleia_agendada", "Assembleia Agendada"),
                    ("assembleia_iniciada", "Assembleia Iniciada"),
                    ("votacao_aberta", "VotaÃ§Ã£o Aberta"),
                    ("procuracao_solicitada", "ProcuraÃ§Ã£o Solicitada"),
                    ("procuracao_confirmada", "ProcuraÃ§Ã£o Confirmada"),
                    ("resultado_publicado", "Resultado Publicado"),
                    ("ata_publicada", "Ata Publicada"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="voto",
            name="opcao",
            field=models.CharField(
                choices=[
                    ("Favor", "A Favor"),
                    ("Contra", "Contra"),
                    ("Abstencao", "AbstenÃ§Ã£o"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CarteiraProfissional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_carteira", models.CharField(max_length=50, unique=True)),
                ("data_emissao", models.DateField()),
                ("data_validade", models.DateField()),
                ("data_renovacao", models.DateField(blank=True, null=True)),
                (
                    "arquivo_pdf",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Activa", "Activa"),
                            ("Expirada", "Expirada"),
                            ("Suspensa", "Suspensa"),
                        ],
                        default="Activa",
                        max_length=15,
                    ),
                ),
                (
                    "despachante",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carteira_profissional",
                        to="users.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carteira Profissional",
                "verbose_name_plural": "Carteiras Profissionais",
                "db_table": "governanca_carteiras_profissionais",
            },
        ),
        migrations.CreateModel(
            name="CertidaoRegularidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_certidao",
                    models.CharField(default=uuid.uuid4, max_length=36, unique=True),
                ),
                ("data_emissao", models.DateTimeField(auto_now_add=True)),
                ("data_validade", models.DateField()),
                (
                    "arquivo_pdf",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "assinatura_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "despachante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certidoes",
                        to="users.usuario",
                    ),
                ),
                (
                    "emitido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certidoes_emitidas",
                        to="users.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certidão de Regularidade",
                "verbose_name_plural": "Certidões de Regularidade",
                "db_table": "governanca_certidoes_regularidade",
                "ordering": ["-data_emissao"],
            },
        ),
        migrations.CreateModel(
            name="EstadoFinanceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Regular", "Regular"),
                            ("Irregular", "Irregular"),
                            ("Suspenso", "Suspenso"),
                        ],
                        default="Regular",
                        max_length=15,
                    ),
                ),
                ("ultima_atualizacao", models.DateTimeField(auto_now=True)),
                ("observacoes", models.TextField(blank=True, default="")),
                (
                    "despachante",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estado_financeiro",
                        to="users.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado Financeiro",
                "verbose_name_plural": "Estados Financeiros",
                "db_table": "governanca_estado_financeiro",
            },
        ),
        migrations.CreateModel(
            name="QuotaConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField()),
                ("mes", models.IntegerField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data_vencimento", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuração de Quota",
                "verbose_name_plural": "Configurações de Quotas",
                "db_table": "governanca_quota_config",
                "unique_together": {("ano", "mes")},
            },
        ),
        migrations.CreateModel(
            name="QuotaGerada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField()),
                ("mes", models.IntegerField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data_vencimento", models.DateField()),
                ("data_pagamento", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Paga", "Paga"),
                            ("Atrasada", "Atrasada"),
                            ("Cancelada", "Cancelada"),
                        ],
                        default="Pendente",
                        max_length=15,
                    ),
                ),
                (
                    "fatura_uuid",
                    models.CharField(default=uuid.uuid4, max_length=36, unique=True),
                ),
                ("observacoes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "despachante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotas",
                        to="users.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quota Gerada",
                "verbose_name_plural": "Quotas Geradas",
                "db_table": "governanca_quotas_geradas",
                "ordering": ["-ano", "-mes"],
                "unique_together": {("despachante", "ano", "mes")},
            },
        ),
        migrations.CreateModel(
            name="PagamentoQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("Multicaixa Express", "Multicaixa Express"),
                            ("Transferencia IBAN", "Transferência IBAN"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "comprovativo",
                    models.FileField(
                        blank=True,
                        default="",
                        max_length=500,
                        upload_to="comprovativos/%Y/%m/",
                    ),
                ),
                ("valor_pago", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "codigo_transferencia",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "iban_origem",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("data_pagamento", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente Confirmacao", "Pendente Confirmação"),
                            ("Confirmado", "Confirmado"),
                            ("Rejeitado", "Rejeitado"),
                        ],
                        default="Pendente Confirmacao",
                        max_length=25,
                    ),
                ),
                ("confirmado_em", models.DateTimeField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True, default="")),
                (
                    "confirmado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagamentos_confirmados",
                        to="users.usuario",
                    ),
                ),
                (
                    "despachante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamentos_quota",
                        to="users.usuario",
                    ),
                ),
                (
                    "quota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamentos",
                        to="governanca.quotagerada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento de Quota",
                "verbose_name_plural": "Pagamentos de Quotas",
                "db_table": "governanca_pagamentos_quota",
                "ordering": ["-data_pagamento"],
            },
        ),
    ]
