# Generated by Django 5.2 on 2026-05-31 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "governanca",
            "0007_alter_notificacao_options_alter_pautavotacao_options_and_more",
        ),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtigoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
                ("titulo", models.CharField(blank=True, default="", max_length=300)),
                ("conteudo", models.TextField(blank=True, default="")),
                ("ordem", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Artigo do Documento",
                "verbose_name_plural": "Artigos do Documento",
                "db_table": "governanca_artigos_documento",
                "ordering": ["ordem", "numero"],
            },
        ),
        migrations.AlterModelOptions(
            name="notificacao",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Notificação",
                "verbose_name_plural": "NotificaçÃµes",
            },
        ),
        migrations.AlterModelOptions(
            name="pautavotacao",
            options={
                "ordering": ["ordem"],
                "verbose_name": "Pauta de Votação",
                "verbose_name_plural": "Pautas de Votação",
            },
        ),
        migrations.AlterModelOptions(
            name="presencaassembleia",
            options={"verbose_name": "Presença", "verbose_name_plural": "Presenças"},
        ),
        migrations.AlterModelOptions(
            name="procuracao",
            options={
                "verbose_name": "Procuração",
                "verbose_name_plural": "ProcuraçÃµes",
            },
        ),
        migrations.AlterField(
            model_name="assembleia",
            name="quorum_minimo",
            field=models.IntegerField(
                default=0, help_text="Número mínimo de presentes para quórum"
            ),
        ),
        migrations.AlterField(
            model_name="assembleia",
            name="status",
            field=models.CharField(
                choices=[
                    ("Agendada", "Agendada"),
                    ("Em Curso", "Em Curso"),
                    ("Concluida", "Concluida"),
                    ("Cancelada", "Cancelada"),
                ],
                default="Agendada",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documentoassembleia",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ata", "Ata"),
                    ("relatorio", "Relatório"),
                    ("outro", "Outro"),
                ],
                default="ata",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="membromesa",
            name="funcao",
            field=models.CharField(
                choices=[
                    ("Presidente", "Presidente"),
                    ("Vice-Presidente", "Vice-Presidente"),
                    ("1º Secretário", "1º Secretário"),
                    ("2º Secretário", "2º Secretário"),
                    ("Secretário", "Secretário"),
                    ("Vogal", "Vogal"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="mensagemchat",
            name="reacao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mao", "Mão ðŸ–\x90ï¸\x8f"),
                    ("palmas", "Palmas ðŸ‘\x8f"),
                    ("coracao", "Coração â\x9d¤ï¸\x8f"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="mensagemchat",
            name="tipo",
            field=models.CharField(
                choices=[("texto", "Texto"), ("reacao", "Reação")],
                default="texto",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notificacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("assembleia_agendada", "Assembleia Agendada"),
                    ("assembleia_iniciada", "Assembleia Iniciada"),
                    ("votacao_aberta", "Votação Aberta"),
                    ("procuracao_solicitada", "Procuração Solicitada"),
                    ("procuracao_confirmada", "Procuração Confirmada"),
                    ("resultado_publicado", "Resultado Publicado"),
                    ("ata_publicada", "Ata Publicada"),
                    ("quota_gerada", "Quota Gerada"),
                    ("pagamento_confirmado", "Pagamento Confirmado"),
                    ("certidao_emitida", "Certidão Emitida"),
                    ("carteira_expirada", "Carteira Expirada"),
                    ("estado_suspenso", "Estado Suspenso"),
                    ("estado_regularizado", "Estado Regularizado"),
                    ("consulta_publicada", "Consulta Publicada"),
                    ("novo_comentario", "Novo Comentário"),
                    ("votacao_aberta", "Votação Aberta"),
                    ("consulta_encerrada", "Consulta Encerrada"),
                    ("relatorio_publicado", "Relatório Publicado"),
                    ("versao_final_publicada", "Versão Final Publicada"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="voto",
            name="opcao",
            field=models.CharField(
                choices=[
                    ("Favor", "A Favor"),
                    ("Contra", "Contra"),
                    ("Abstencao", "Abstenção"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artigo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="governanca.artigodocumento",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios_consulta",
                        to="users.usuario",
                    ),
                ),
                (
                    "resposta_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="governanca.comentario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentário",
                "verbose_name_plural": "Comentários",
                "db_table": "governanca_comentarios_consulta",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultaPublica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("descricao", models.TextField(blank=True, default="")),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        default="",
                        max_length=500,
                        upload_to="consultas_publicas/%Y/%m/",
                    ),
                ),
                ("prazo_fim", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Rascunho", "Rascunho"),
                            ("Publicada", "Publicada"),
                            ("EmVotacao", "Em Votação"),
                            ("Encerrada", "Encerrada"),
                            ("Aprovada", "Aprovada (Versão Final)"),
                            ("Rejeitada", "Rejeitada"),
                        ],
                        default="Rascunho",
                        max_length=20,
                    ),
                ),
                ("publicado_em", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas_criadas",
                        to="users.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta Pública",
                "verbose_name_plural": "Consultas Públicas",
                "db_table": "governanca_consultas_publicas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="artigodocumento",
            name="consulta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artigos",
                to="governanca.consultapublica",
            ),
        ),
        migrations.CreateModel(
            name="RelatorioConsulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conteudo", models.JSONField(blank=True, default=dict)),
                (
                    "assinatura_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "arquivo_pdf",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "consulta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relatorio",
                        to="governanca.consultapublica",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório de Consulta",
                "verbose_name_plural": "Relatórios de Consulta",
                "db_table": "governanca_relatorios_consulta",
            },
        ),
        migrations.CreateModel(
            name="VotacaoConsulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateTimeField(auto_now_add=True)),
                ("data_fim", models.DateTimeField(blank=True, null=True)),
                ("ativa", models.BooleanField(default=True)),
                (
                    "consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votacoes",
                        to="governanca.consultapublica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Votação de Consulta",
                "verbose_name_plural": "Votações de Consulta",
                "db_table": "governanca_votacoes_consulta",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="artigodocumento",
            unique_together={("consulta", "numero")},
        ),
        migrations.CreateModel(
            name="VotoConsulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voto",
                    models.CharField(
                        choices=[
                            ("Favor", "Favor"),
                            ("Contra", "Contra"),
                            ("Abstencao", "Abstenção"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votos_consulta",
                        to="users.usuario",
                    ),
                ),
                (
                    "votacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votos",
                        to="governanca.votacaoconsulta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voto em Consulta",
                "verbose_name_plural": "Votos em Consulta",
                "db_table": "governanca_votos_consulta",
                "unique_together": {("votacao", "usuario")},
            },
        ),
    ]
