# Generated by Django 5.2 on 2026-05-31 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanca", "0008_artigodocumento_alter_notificacao_options_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assembleia",
            name="max_procuracao",
            field=models.IntegerField(
                default=1, help_text="Máximo de procurações que um membro pode receber"
            ),
        ),
        migrations.AddField(
            model_name="atadigital",
            name="assinado_presidente_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="atadigital",
            name="assinado_secretario_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="atadigital",
            name="assinatura_hash_presidente",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="atadigital",
            name="assinatura_hash_secretario",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="atadigital",
            name="status_assinatura",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aguardando Presidente", "Aguardando Presidente"),
                    ("Aguardando Secretario", "Aguardando Secretário"),
                    ("Assinada", "Assinada"),
                    ("Publicada", "Publicada"),
                ],
                default="Pendente",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="pautavotacao",
            name="reaberta",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pautavotacao",
            name="reaberta_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("assembleia_agendada", "Assembleia Agendada"),
                    ("assembleia_iniciada", "Assembleia Iniciada"),
                    ("votacao_aberta", "Votação Aberta"),
                    ("procuracao_solicitada", "Procuração Solicitada"),
                    ("procuracao_confirmada", "Procuração Confirmada"),
                    ("resultado_publicado", "Resultado Publicado"),
                    ("ata_publicada", "Ata Publicada"),
                    ("quota_gerada", "Quota Gerada"),
                    ("pagamento_confirmado", "Pagamento Confirmado"),
                    ("certidao_emitida", "Certidão Emitida"),
                    ("carteira_expirada", "Carteira Expirada"),
                    ("estado_suspenso", "Estado Suspenso"),
                    ("estado_regularizado", "Estado Regularizado"),
                    ("consulta_publicada", "Consulta Publicada"),
                    ("novo_comentario", "Novo Comentário"),
                    ("votacao_aberta", "Votação Aberta"),
                    ("consulta_encerrada", "Consulta Encerrada"),
                    ("relatorio_publicado", "Relatório Publicado"),
                    ("versao_final_publicada", "Versão Final Publicada"),
                    ("convocatoria_publicada", "Convocatória Publicada"),
                    ("votacao_reaberta", "Votação Reaberta"),
                    ("ata_assinada", "Ata Assinada"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Convocatoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("descricao", models.TextField(blank=True, default="")),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        default="",
                        max_length=500,
                        upload_to="convocatorias/%Y/%m/",
                    ),
                ),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                ("prazo_confirmacao", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Rascunho", "Rascunho"), ("Publicada", "Publicada")],
                        default="Rascunho",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assembleia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convocatorias",
                        to="governanca.assembleia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Convocatória",
                "verbose_name_plural": "Convocatórias",
                "db_table": "governanca_convocatorias",
                "ordering": ["-data_envio"],
            },
        ),
        migrations.CreateModel(
            name="LogAssembleia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada"),
                            ("saida", "Saída"),
                            ("reconexao", "Reconexão"),
                            ("procuracao_solicitada", "Procuração Solicitada"),
                            ("procuracao_confirmada", "Procuração Confirmada"),
                            ("votacao", "Votação"),
                            ("votacao_aberta", "Votação Aberta"),
                            ("votacao_encerrada", "Votação Encerrada"),
                            ("votacao_reaberta", "Votação Reaberta"),
                            ("encerramento", "Encerramento"),
                            ("reabertura", "Reabertura"),
                            ("criacao", "Criação"),
                            ("edicao", "Edição"),
                            ("assembleia_iniciada", "Assembleia Iniciada"),
                            ("assembleia_concluida", "Assembleia Concluída"),
                            ("assembleia_cancelada", "Assembleia Cancelada"),
                        ],
                        max_length=30,
                    ),
                ),
                ("detalhes", models.JSONField(blank=True, default=dict)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assembleia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="governanca.assembleia",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log da Assembleia",
                "verbose_name_plural": "Logs da Assembleia",
                "db_table": "governanca_logs_assembleia",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["assembleia", "created_at"],
                        name="governanca__assembl_514adf_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RespostaPresenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resposta",
                    models.CharField(
                        choices=[("Sim", "Sim"), ("Nao", "Não"), ("Talvez", "Talvez")],
                        max_length=10,
                    ),
                ),
                ("respondido_em", models.DateTimeField(auto_now_add=True)),
                (
                    "assembleia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas_presenca",
                        to="governanca.assembleia",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas_presenca",
                        to="users.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta de Presença",
                "verbose_name_plural": "Respostas de Presença",
                "db_table": "governanca_respostas_presenca",
                "unique_together": {("assembleia", "usuario")},
            },
        ),
    ]
