# Generated by Django 5.2 on 2026-05-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanca", "0009_assembleia_max_procuracao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotaconfig",
            name="ativa",
            field=models.BooleanField(
                default=True,
                help_text="Se ativa, a configuração está disponível para geração de quotas",
            ),
        ),
        migrations.AddField(
            model_name="quotaconfig",
            name="juros_atraso",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                help_text="Percentagem de juros ao dia (ex: 0.5)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="quotaconfig",
            name="multa_atraso",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Valor fixo de multa por atraso (Kz)",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="quotaconfig",
            name="periodicidade",
            field=models.CharField(
                choices=[
                    ("Mensal", "Mensal"),
                    ("Trimestral", "Trimestral"),
                    ("Semestral", "Semestral"),
                    ("Anual", "Anual"),
                ],
                default="Mensal",
                max_length=15,
            ),
        ),
    ]
