# Generated by Django 5.2 on 2026-05-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanca", "0010_quotaconfig_ativa_quotaconfig_juros_atraso_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotaconfig",
            name="juros_atraso",
        ),
        migrations.RemoveField(
            model_name="quotaconfig",
            name="multa_atraso",
        ),
        migrations.RemoveField(
            model_name="quotaconfig",
            name="periodicidade",
        ),
        migrations.AddField(
            model_name="quotaconfig",
            name="multa_percentual",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                help_text="Percentagem de multa ao dia sobre o valor da quota (ex: 0.50 = 0.5%)",
                max_digits=5,
            ),
        ),
    ]
