# Generated by Django 5.2 on 2026-06-02 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanca", "0015_add_critical_indexes"),
        ("users", "0005_add_secretario_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaMembro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("isento", models.BooleanField(default=False)),
                ("ordem", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Categoria de Membro",
                "verbose_name_plural": "Categorias de Membro",
                "db_table": "governanca_categorias_membro",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="IsencaoMembro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("motivo", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Isenção de Membro",
                "verbose_name_plural": "Isenções de Membro",
                "db_table": "governanca_isencoes_membro",
            },
        ),
        migrations.CreateModel(
            name="TipoQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("recorrente", models.BooleanField(default=False)),
                ("dias_intervalo", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tipo de Quota",
                "verbose_name_plural": "Tipos de Quota",
                "db_table": "governanca_tipos_quota",
                "ordering": ["pk"],
            },
        ),
        migrations.RemoveIndex(
            model_name="assembleia",
            name="idx_assem_status_data",
        ),
        migrations.RemoveIndex(
            model_name="notificacao",
            name="idx_notif_usuario_lida",
        ),
        migrations.RemoveIndex(
            model_name="quotagerada",
            name="idx_quota_ano_mes_status",
        ),
        migrations.AlterUniqueTogether(
            name="quotaconfig",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="quotagerada",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="quotagerada",
            name="descricao",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="quotagerada",
            name="periodo_fim",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quotagerada",
            name="periodo_inicio",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assembleia",
            name="data_hora",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="assembleia",
            name="status",
            field=models.CharField(
                choices=[
                    ("Agendada", "Agendada"),
                    ("Em Curso", "Em Curso"),
                    ("Concluida", "Concluida"),
                    ("Cancelada", "Cancelada"),
                ],
                default="Agendada",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="atadigital",
            name="status_assinatura",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aguardando Presidente", "Aguardando Presidente"),
                    ("Aguardando Secretario", "Aguardando Secretário"),
                    ("Assinada", "Assinada"),
                    ("Publicada", "Publicada"),
                ],
                default="Pendente",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="consultapublica",
            name="status",
            field=models.CharField(
                choices=[
                    ("Rascunho", "Rascunho"),
                    ("Publicada", "Publicada"),
                    ("EmVotacao", "Em Votação"),
                    ("Encerrada", "Encerrada"),
                    ("Aprovada", "Aprovada (Versão Final)"),
                    ("Rejeitada", "Rejeitada"),
                ],
                default="Rascunho",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="estadofinanceiro",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Regular", "Regular"),
                    ("Irregular", "Irregular"),
                    ("Suspenso", "Suspenso"),
                ],
                default="Regular",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="notificacao",
            name="lida",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notificacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("assembleia_agendada", "Assembleia Agendada"),
                    ("assembleia_iniciada", "Assembleia Iniciada"),
                    ("votacao_aberta", "Votação Aberta"),
                    ("procuracao_solicitada", "Procuração Solicitada"),
                    ("procuracao_confirmada", "Procuração Confirmada"),
                    ("resultado_publicado", "Resultado Publicado"),
                    ("ata_publicada", "Ata Publicada"),
                    ("quota_gerada", "Quota Gerada"),
                    ("pagamento_confirmado", "Pagamento Confirmado"),
                    ("certidao_emitida", "Certidão Emitida"),
                    ("carteira_expirada", "Carteira Expirada"),
                    ("estado_suspenso", "Estado Suspenso"),
                    ("estado_regularizado", "Estado Regularizado"),
                    ("consulta_publicada", "Consulta Publicada"),
                    ("novo_comentario", "Novo Comentário"),
                    ("votacao_aberta", "Votação Aberta"),
                    ("consulta_encerrada", "Consulta Encerrada"),
                    ("relatorio_publicado", "Relatório Publicado"),
                    ("versao_final_publicada", "Versão Final Publicada"),
                    ("convocatoria_publicada", "Convocatória Publicada"),
                    ("votacao_reaberta", "Votação Reaberta"),
                    ("ata_assinada", "Ata Assinada"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="pagamentoquota",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente Confirmacao", "Pendente Confirmação"),
                    ("Confirmado", "Confirmado"),
                    ("Rejeitado", "Rejeitado"),
                ],
                default="Pendente Confirmacao",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="pautavotacao",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Em Votacao", "Em Votacao"),
                    ("Concluida", "Concluida"),
                ],
                default="Pendente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="quotaconfig",
            name="mes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quotagerada",
            name="ano",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quotagerada",
            name="mes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quotagerada",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Paga", "Paga"),
                    ("Atrasada", "Atrasada"),
                    ("Cancelada", "Cancelada"),
                ],
                default="Pendente",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="quotaconfig",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanca.categoriamembro",
            ),
        ),
        migrations.AddField(
            model_name="isencaomembro",
            name="aprovado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="isencoes_aprovadas",
                to="users.usuario",
            ),
        ),
        migrations.AddField(
            model_name="isencaomembro",
            name="despachante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="isencoes",
                to="users.usuario",
            ),
        ),
        migrations.AddField(
            model_name="isencaomembro",
            name="tipo_quota",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanca.tipoquota",
            ),
        ),
        migrations.AddField(
            model_name="quotaconfig",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanca.tipoquota",
            ),
        ),
        migrations.AddField(
            model_name="quotagerada",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanca.tipoquota",
            ),
        ),
    ]
