# Generated by Django 5.2 on 2026-06-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanca", "0017_seed_tipos_categorias"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentoassembleia",
            name="conteudo",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="documentoassembleia",
            name="arquivo",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="documentos_assembleia/%Y/%m/",
            ),
        ),
    ]
