# Generated by Django 5.2 on 2026-06-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "governanca",
            "0020_alter_assembleia_data_hora_alter_assembleia_status_and_more",
        ),
        ("users", "0007_alter_usuario_papel_alter_usuario_status_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mensagemchat",
            index=models.Index(
                fields=["assembleia", "-created_at"], name="idx_chat_assembleia_data"
            ),
        ),
    ]
