# Generated by Django 5.2 on 2026-06-03 09:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanca", "0021_mensagemchat_idx_chat_assembleia_data"),
        ("users", "0007_alter_usuario_papel_alter_usuario_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamentoquota",
            name="status_anterior_quota",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Estado da quota antes da submissão do pagamento (para reverter se rejeitado)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="quotaconfig",
            name="dias_carencia",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Dias de tolerância após vencimento antes de aplicar multa",
            ),
        ),
        migrations.AddField(
            model_name="quotaconfig",
            name="dias_limite_retroativo",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Máximo de meses retroativos permitidos (deixar vazio = sem limite)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quotaconfig",
            name="permite_retroativo",
            field=models.BooleanField(
                default=False, help_text="Se ativa, permite gerar quotas retroativas"
            ),
        ),
        migrations.AddField(
            model_name="quotagerada",
            name="data_envio",
            field=models.DateField(
                blank=True,
                help_text="Data em que a quota foi enviada ao membro",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quotagerada",
            name="referencia",
            field=models.CharField(
                blank=True,
                help_text="Referência amigável (ex: QUOTA-MENSAL-06-2026-00001)",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="quotagerada",
            name="valor_multa",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="quotagerada",
            name="valor_original",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor base sem multa",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quotagerada",
            name="valor_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor original + multa",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pagamentoquota",
            name="metodo",
            field=models.CharField(
                choices=[
                    ("Multicaixa Express", "Multicaixa Express"),
                    ("Transferencia IBAN", "Transferência IBAN"),
                    ("Deposito Bancario", "Depósito Bancário"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="quotagerada",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Atrasada", "Atrasada"),
                    ("Pendente Confirmacao", "Pendente Confirmação"),
                    ("Paga", "Paga"),
                    ("Cancelada", "Cancelada"),
                    ("Isenta", "Isenta"),
                ],
                db_index=True,
                default="Pendente",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="HistoricoQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("QUOTA_GERADA", "Quota Gerada"),
                            ("QUOTA_VENCIDA", "Quota Vencida"),
                            ("PAGAMENTO_SUBMETIDO", "Pagamento Submetido"),
                            ("PAGAMENTO_APROVADO", "Pagamento Aprovado"),
                            ("PAGAMENTO_REJEITADO", "Pagamento Rejeitado"),
                            ("QUOTA_CANCELADA", "Quota Cancelada"),
                            ("QUOTA_ISENTADA", "Quota Isentada"),
                            ("ISENCAO_CRIADA", "Isenção Criada"),
                            ("ISENCAO_REMOVIDA", "Isenção Removida"),
                            (
                                "ESTADO_FINANCEIRO_ALTERADO",
                                "Estado Financeiro Alterado",
                            ),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("descricao", models.TextField(blank=True, default="")),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "membro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_quotas",
                        to="users.usuario",
                    ),
                ),
                (
                    "pagamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historico",
                        to="governanca.pagamentoquota",
                    ),
                ),
                (
                    "quota",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historico",
                        to="governanca.quotagerada",
                    ),
                ),
                (
                    "utilizador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historico_quotas_acao",
                        to="users.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Quota",
                "verbose_name_plural": "Históricos de Quotas",
                "db_table": "governanca_historico_quotas",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["membro", "created_at"],
                        name="governanca__membro__778f35_idx",
                    ),
                    models.Index(
                        fields=["quota", "created_at"],
                        name="governanca__quota_i_9bcc3a_idx",
                    ),
                ],
            },
        ),
    ]
