# Generated by Django 5.2 on 2026-06-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("governanca", "0022_pagamentoquota_status_anterior_quota_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quotaconfig",
            old_name="dias_limite_retroativo",
            new_name="meses_limite_retroativo",
        ),
    ]
