# Generated by Django 5.2 on 2026-06-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "governanca",
            "0023_rename_dias_limite_retroativo_quotaconfig_meses_limite_retroativo",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotaconfig",
            name="meses_limite_retroativo",
        ),
        migrations.RemoveField(
            model_name="quotaconfig",
            name="permite_retroativo",
        ),
    ]
