# Generated by Django 5.2 on 2026-06-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("governanca", "0024_remove_quotaconfig_meses_limite_retroativo_and_more"),
        ("users", "0007_alter_usuario_papel_alter_usuario_status_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="voto",
            unique_together={("pauta", "usuario", "em_delegacao", "delegado_de")},
        ),
    ]
