# Generated by Django 5.2 on 2026-06-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanca", "0025_altera_unique_together_voto_delegado_de"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("assembleia_agendada", "Assembleia Agendada"),
                    ("assembleia_iniciada", "Assembleia Iniciada"),
                    ("votacao_aberta", "Votação Aberta"),
                    ("procuracao_solicitada", "Procuração Solicitada"),
                    ("procuracao_confirmada", "Procuração Confirmada"),
                    ("resultado_publicado", "Resultado Publicado"),
                    ("ata_publicada", "Ata Publicada"),
                    ("quota_gerada", "Quota Gerada"),
                    ("pagamento_confirmado", "Pagamento Confirmado"),
                    ("certidao_emitida", "Certidão Emitida"),
                    ("carteira_expirada", "Carteira Expirada"),
                    ("estado_suspenso", "Estado Suspenso"),
                    ("estado_regularizado", "Estado Regularizado"),
                    ("consulta_publicada", "Consulta Publicada"),
                    ("novo_comentario", "Novo Comentário"),
                    ("votacao_aberta", "Votação Aberta"),
                    ("consulta_encerrada", "Consulta Encerrada"),
                    ("relatorio_publicado", "Relatório Publicado"),
                    ("versao_final_publicada", "Versão Final Publicada"),
                    ("convocatoria_publicada", "Convocatória Publicada"),
                    ("votacao_reaberta", "Votação Reaberta"),
                    ("ata_assinada", "Ata Assinada"),
                    ("cargo_atribuido", "Cargo Atribuído"),
                    ("cargo_removido", "Cargo Removido"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
