# Generated by Django 5.2 on 2026-06-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanca", "0026_alter_notificacao_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="assembleia",
            name="ultima_actividade",
            field=models.DateTimeField(
                blank=True,
                help_text="Última actividade (chat, voto, presença) para detecting inactividade",
                null=True,
            ),
        ),
    ]
