# Generated by Django 5.2 on 2026-06-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanca", "0027_assembleia_ultima_actividade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="isencaomembro",
            name="data_fim",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="isencaomembro",
            name="data_inicio",
            field=models.DateField(db_index=True),
        ),
    ]
