# Generated by Django 5.2 on 2026-06-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanca", "0028_add_isencao_data_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacao",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
