# Generated by Django 5.2 on 2026-06-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanca", "0029_add_db_index_to_query_fields"),
        ("users", "0029_add_db_index_to_query_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notificacao",
            index=models.Index(
                fields=["usuario", "-created_at"], name="ix_notificacoes_usuario_data"
            ),
        ),
    ]
