# Generated by Django 4.2.30 on 2026-06-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanca', '0030_add_composite_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotagerada',
            name='referencia',
            field=models.CharField(blank=True, default='', help_text='Referência amigável (ex: QUOTA-MENSAL-06-2026-00001)', max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='quotaconfig',
            unique_together={('categoria', 'tipo', 'ano', 'mes')},
        ),
    ]
