# Generated by Django 4.2.30 on 2026-06-25 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanca', '0031_alter_quotagerada_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigodocumento',
            name='ordem',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='atadigital',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='categoriamembro',
            name='nome',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='categoriamembro',
            name='ordem',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='certidaoregularidade',
            name='data_emissao',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='consultapublica',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='consultapublica',
            name='documento',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='consultas_publicas/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='documentoassembleia',
            name='arquivo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='documentos_assembleia/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='documentoassembleia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='membromesa',
            name='ordem',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='pagamentoquota',
            name='data_pagamento',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pautavotacao',
            name='ordem',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='quotaconfig',
            name='ano',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='quotaconfig',
            name='ativa',
            field=models.BooleanField(db_index=True, default=True, help_text='Se ativa, a configuração está disponível para geração de quotas'),
        ),
        migrations.AlterField(
            model_name='quotaconfig',
            name='mes',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='votacaoconsulta',
            name='data_inicio',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
