# Generated by Django 5.2 on 2026-06-09 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aduaneiro", "0004_alter_declaracaounica_status"),
        ("clientes", "0006_cliente_limite_financeiro"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequisicaoFundo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_requisicao",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número da Requisição"
                    ),
                ),
                (
                    "valor_solicitado",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Solicitado"
                    ),
                ),
                ("justificacao", models.TextField(verbose_name="Justificação")),
                ("data", models.DateTimeField(auto_now_add=True, verbose_name="Data")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Em Aprovação", "Em Aprovação"),
                            ("Aprovada", "Aprovada"),
                            ("Rejeitada", "Rejeitada"),
                            ("Cancelada", "Cancelada"),
                        ],
                        default="Pendente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "documento_justificativo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="requisicoes_fundos/",
                        verbose_name="Documento Justificativo",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisicoes_fundos",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "processo_aduaneiro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisicoes_fundos",
                        to="aduaneiro.declaracaounica",
                        verbose_name="Processo Aduaneiro",
                    ),
                ),
                (
                    "responsavel_aprovacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aprovacoes_fundos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável pela Aprovação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisição de Fundo",
                "verbose_name_plural": "Requisições de Fundos",
                "db_table": "financeiro_requisicao_fundo",
                "ordering": ["-data"],
            },
        ),
    ]
