# Generated by Django 5.2 on 2026-06-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requisicaofundo",
            name="responsavel_aprovacao",
        ),
        migrations.AddField(
            model_name="requisicaofundo",
            name="responsavel_aprovacao_id_usuario",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="ID do Aprovador"
            ),
        ),
        migrations.AddField(
            model_name="requisicaofundo",
            name="responsavel_aprovacao_nome",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Nome do Aprovador"
            ),
        ),
        migrations.AddField(
            model_name="requisicaofundo",
            name="solicitante_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="ID do Solicitante"
            ),
        ),
        migrations.AddField(
            model_name="requisicaofundo",
            name="solicitante_nome",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Nome do Solicitante",
            ),
        ),
        migrations.AlterField(
            model_name="requisicaofundo",
            name="numero_requisicao",
            field=models.CharField(
                blank=True,
                max_length=50,
                unique=True,
                verbose_name="Número da Requisição",
            ),
        ),
    ]
