# Generated by Django 5.2 on 2026-06-09 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aduaneiro", "0004_alter_declaracaounica_status"),
        ("clientes", "0007_cliente_saldo_conta_corrente"),
        ("financeiro", "0002_remove_requisicaofundo_responsavel_aprovacao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacturaCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_factura",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Número da Factura",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Total"
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Valor Pago",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Parcialmente Paga", "Parcialmente Paga"),
                            ("Paga", "Paga"),
                            ("Cancelada", "Cancelada"),
                        ],
                        default="Pendente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "data_emissao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Emissão"
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="Data de Vencimento"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "criado_por_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID do Criador"
                    ),
                ),
                (
                    "criado_por_nome",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Nome do Criador",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facturas_cliente",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "processo_aduaneiro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facturas_cliente",
                        to="aduaneiro.declaracaounica",
                        verbose_name="Processo Aduaneiro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura de Cliente",
                "verbose_name_plural": "Facturas de Clientes",
                "db_table": "financeiro_factura_cliente",
                "ordering": ["-data_emissao"],
            },
        ),
        migrations.CreateModel(
            name="ReciboCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_recibo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Número do Recibo",
                    ),
                ),
                (
                    "valor_recebido",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Recebido"
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("Transferência Bancária", "Transferência Bancária"),
                            ("Multicaixa", "Multicaixa"),
                            ("TPAs", "TPAs"),
                            ("Depósito Bancário", "Depósito Bancário"),
                            ("Numerário", "Numerário"),
                        ],
                        max_length=50,
                        verbose_name="Forma de Pagamento",
                    ),
                ),
                ("data_pagamento", models.DateField(verbose_name="Data do Pagamento")),
                (
                    "referencia_bancaria",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Referência Bancária",
                    ),
                ),
                (
                    "utilizador_responsavel_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID do Responsável"
                    ),
                ),
                (
                    "utilizador_responsavel_nome",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Nome do Responsável",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recibos_cliente",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recibos",
                        to="financeiro.facturacliente",
                        verbose_name="Factura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recibo de Cliente",
                "verbose_name_plural": "Recibos de Clientes",
                "db_table": "financeiro_recibo_cliente",
                "ordering": ["-data_criacao"],
            },
        ),
    ]
