# Generated by Django 5.2 on 2026-06-09 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0007_cliente_saldo_conta_corrente"),
        ("financeiro", "0003_facturacliente_recibocliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturacliente",
            name="despesas_operacionais",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Despesas Operacionais",
            ),
        ),
        migrations.AddField(
            model_name="facturacliente",
            name="emolumentos",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, verbose_name="Emolumentos"
            ),
        ),
        migrations.AddField(
            model_name="facturacliente",
            name="honorarios_despachante",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Honorários do Despachante",
            ),
        ),
        migrations.AddField(
            model_name="facturacliente",
            name="iva",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, verbose_name="IVA"
            ),
        ),
        migrations.AddField(
            model_name="facturacliente",
            name="outros_encargos",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Outros Encargos",
            ),
        ),
        migrations.AddField(
            model_name="facturacliente",
            name="taxas_aduaneiras",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Taxas Aduaneiras",
            ),
        ),
        migrations.CreateModel(
            name="FacturaRecibo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_factura_recibo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Número da Factura-Recibo",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("Transferência Bancária", "Transferência Bancária"),
                            ("Multicaixa", "Multicaixa"),
                            ("TPAs", "TPAs"),
                            ("Depósito Bancário", "Depósito Bancário"),
                            ("Numerário", "Numerário"),
                        ],
                        max_length=50,
                        verbose_name="Forma de Pagamento",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "estado",
                    models.CharField(
                        choices=[("Paga", "Paga"), ("Cancelada", "Cancelada")],
                        default="Paga",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "utilizador_responsavel_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID do Responsável"
                    ),
                ),
                (
                    "utilizador_responsavel_nome",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Nome do Responsável",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facturas_recibo",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura-Recibo",
                "verbose_name_plural": "Facturas-Recibo",
                "db_table": "financeiro_factura_recibo",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="NotaCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_nota",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Número da Nota",
                    ),
                ),
                (
                    "valor_creditado",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Creditado"
                    ),
                ),
                ("motivo", models.CharField(max_length=255, verbose_name="Motivo")),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Aprovada", "Aprovada"),
                            ("Rejeitada", "Rejeitada"),
                            ("Cancelada", "Cancelada"),
                        ],
                        default="Pendente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "utilizador_criador_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID do Criador"
                    ),
                ),
                (
                    "utilizador_criador_nome",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Nome do Criador",
                    ),
                ),
                (
                    "utilizador_aprovador_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID do Aprovador"
                    ),
                ),
                (
                    "utilizador_aprovador_nome",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Nome do Aprovador",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_aprovacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Aprovação"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_credito",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "factura_relacionada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_credito",
                        to="financeiro.facturacliente",
                        verbose_name="Factura Relacionada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Crédito",
                "verbose_name_plural": "Notas de Crédito",
                "db_table": "financeiro_nota_credito",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="NotaDebito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_nota",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Número da Nota",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                ("motivo", models.CharField(max_length=255, verbose_name="Motivo")),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "utilizador_criador_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID do Criador"
                    ),
                ),
                (
                    "utilizador_criador_nome",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Nome do Criador",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_debito",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "factura_relacionada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_debito",
                        to="financeiro.facturacliente",
                        verbose_name="Factura Relacionada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Débito",
                "verbose_name_plural": "Notas de Débito",
                "db_table": "financeiro_nota_debito",
                "ordering": ["-data_criacao"],
            },
        ),
    ]
