# Generated by Django 5.2 on 2026-06-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0004_facturacliente_despesas_operacionais_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notadebito",
            name="data_aprovacao",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data de Aprovação"
            ),
        ),
        migrations.AddField(
            model_name="notadebito",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aprovada", "Aprovada"),
                    ("Rejeitada", "Rejeitada"),
                    ("Cancelada", "Cancelada"),
                ],
                default="Pendente",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AddField(
            model_name="notadebito",
            name="utilizador_aprovador_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="ID do Aprovador"
            ),
        ),
        migrations.AddField(
            model_name="notadebito",
            name="utilizador_aprovador_nome",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Nome do Aprovador"
            ),
        ),
    ]
