# Generated by Django 5.2 on 2026-06-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0005_notadebito_data_aprovacao_notadebito_estado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoFinanceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("Requisicao", "Requisição"),
                            ("Factura", "Factura"),
                            ("Recibo", "Recibo"),
                            ("NotaCredito", "Nota de Crédito"),
                            ("NotaDebito", "Nota de Débito"),
                            ("FacturaRecibo", "Factura-Recibo"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                ("documento_id", models.IntegerField(verbose_name="ID do Documento")),
                (
                    "documento_numero",
                    models.CharField(max_length=50, verbose_name="Número do Documento"),
                ),
                (
                    "cliente_nome",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Nome do Cliente",
                    ),
                ),
                ("accao", models.CharField(max_length=50, verbose_name="Ação")),
                (
                    "estado_anterior",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Estado Anterior",
                    ),
                ),
                (
                    "estado_novo",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Estado Novo",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor",
                    ),
                ),
                (
                    "utilizador_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID do Utilizador"
                    ),
                ),
                (
                    "utilizador_nome",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Nome do Utilizador",
                    ),
                ),
                (
                    "data",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora"),
                ),
            ],
            options={
                "verbose_name": "Histórico Financeiro",
                "verbose_name_plural": "Históricos Financeiros",
                "db_table": "financeiro_historico",
                "ordering": ["-data"],
            },
        ),
    ]
