# Generated by Django 5.2 on 2026-06-11 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0006_historicofinanceiro"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturarecibo",
            name="factura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facturas_recibo",
                to="financeiro.facturacliente",
                verbose_name="Factura Associada",
            ),
        ),
    ]
