# Generated by Django 5.2 on 2026-06-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0008_requisicaofundo_motivo_rejeicao_recibocliente_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facturacliente",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Parcialmente Paga", "Parcialmente Paga"),
                    ("Paga", "Paga"),
                    ("Cancelada", "Cancelada"),
                ],
                db_index=True,
                default="Pendente",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="facturarecibo",
            name="estado",
            field=models.CharField(
                choices=[("Paga", "Paga"), ("Cancelada", "Cancelada")],
                db_index=True,
                default="Paga",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="historicofinanceiro",
            name="documento_id",
            field=models.IntegerField(db_index=True, verbose_name="ID do Documento"),
        ),
        migrations.AlterField(
            model_name="historicofinanceiro",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("Requisicao", "Requisição"),
                    ("Factura", "Factura"),
                    ("Recibo", "Recibo"),
                    ("NotaCredito", "Nota de Crédito"),
                    ("NotaDebito", "Nota de Débito"),
                    ("FacturaRecibo", "Factura-Recibo"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AlterField(
            model_name="notacredito",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aprovada", "Aprovada"),
                    ("Rejeitada", "Rejeitada"),
                    ("Cancelada", "Cancelada"),
                ],
                db_index=True,
                default="Pendente",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="notadebito",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aprovada", "Aprovada"),
                    ("Rejeitada", "Rejeitada"),
                    ("Cancelada", "Cancelada"),
                ],
                db_index=True,
                default="Pendente",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="recibocliente",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[("Pendente", "Pendente"), ("Cancelado", "Cancelado")],
                db_index=True,
                default=None,
                max_length=20,
                null=True,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="requisicaofundo",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Em Aprovação", "Em Aprovação"),
                    ("Aprovada", "Aprovada"),
                    ("Rejeitada", "Rejeitada"),
                    ("Cancelada", "Cancelada"),
                ],
                db_index=True,
                default="Pendente",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AddIndex(
            model_name="historicofinanceiro",
            index=models.Index(
                fields=["tipo_documento", "documento_id"], name="idx_historico_tipo_doc"
            ),
        ),
    ]
