# Generated by Django 5.2 on 2026-06-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0009_add_estado_and_historico_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facturacliente",
            name="data_vencimento",
            field=models.DateField(db_index=True, verbose_name="Data de Vencimento"),
        ),
        migrations.AlterField(
            model_name="historicofinanceiro",
            name="data",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Data/Hora"
            ),
        ),
        migrations.AlterField(
            model_name="requisicaofundo",
            name="data",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Data"
            ),
        ),
    ]
