# Generated by Django 5.2 on 2026-06-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aduaneiro", "0007_add_composite_indexes"),
        ("clientes", "0008_add_nome_email_ativo_indexes"),
        ("financeiro", "0010_add_db_index_to_query_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="facturacliente",
            index=models.Index(
                fields=["estado", "-data_emissao"], name="ix_factura_estado_data"
            ),
        ),
    ]
