# Generated by Django 5.2 on 2026-06-13 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0011_add_composite_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="requisicaofundo",
            name="nivel_atual",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Nível Actual"
            ),
        ),
        migrations.CreateModel(
            name="FluxoAprovacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Fluxo"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, default="", verbose_name="Descrição"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fluxo de Aprovação",
                "verbose_name_plural": "Fluxos de Aprovação",
                "db_table": "financeiro_fluxo_aprovacao",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="requisicaofundo",
            name="fluxo_aprovacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requisicoes",
                to="financeiro.fluxoaprovacao",
                verbose_name="Fluxo de Aprovação",
            ),
        ),
        migrations.CreateModel(
            name="NivelAprovacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveSmallIntegerField(verbose_name="Ordem")),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Nível"),
                ),
                (
                    "qtde_aprovadores",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Quantidade de Aprovadores Necessários"
                    ),
                ),
                (
                    "fluxo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="niveis",
                        to="financeiro.fluxoaprovacao",
                        verbose_name="Fluxo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nível de Aprovação",
                "verbose_name_plural": "Níveis de Aprovação",
                "db_table": "financeiro_nivel_aprovacao",
                "ordering": ["fluxo", "ordem"],
                "unique_together": {("fluxo", "ordem")},
            },
        ),
        migrations.CreateModel(
            name="AprovadorNivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="niveis_aprovacao",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilizador",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aprovadores",
                        to="financeiro.nivelaprovacao",
                        verbose_name="Nível",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aprovador do Nível",
                "verbose_name_plural": "Aprovadores do Nível",
                "db_table": "financeiro_aprovador_nivel",
                "unique_together": {("nivel", "usuario")},
            },
        ),
        migrations.CreateModel(
            name="AprovacaoRequisicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Aprovada", "Aprovada"),
                            ("Rejeitada", "Rejeitada"),
                        ],
                        db_index=True,
                        default="Pendente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, default="", verbose_name="Observação"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "respondida_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Respondida em"
                    ),
                ),
                (
                    "aprovador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votos_aprovacao",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovador",
                    ),
                ),
                (
                    "requisicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aprovacoes",
                        to="financeiro.requisicaofundo",
                        verbose_name="Requisição",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aprovacoes",
                        to="financeiro.nivelaprovacao",
                        verbose_name="Nível",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aprovação de Requisição",
                "verbose_name_plural": "Aprovações de Requisições",
                "db_table": "financeiro_aprovacao_requisicao",
                "ordering": ["nivel__ordem", "created_at"],
                "unique_together": {("requisicao", "nivel", "aprovador")},
            },
        ),
    ]
