# Generated by Django 5.2 on 2026-06-13 23:23

import django.db.models.deletion
from django.db import migrations, models


def migrar_funcao_para_nivel(apps, schema_editor):
    AprovadorNivel = apps.get_model('financeiro', 'AprovadorNivel')
    NivelAprovacao = apps.get_model('financeiro', 'NivelAprovacao')
    for nivel in NivelAprovacao.objects.all():
        ap = AprovadorNivel.objects.filter(nivel=nivel).first()
        if ap and ap.funcao_id:
            nivel.funcao_id = ap.funcao_id
            nivel.save(update_fields=['funcao_id'])


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0013_clean_aprovadornivel_funcao"),
        ("users", "0030_fix_remove_papeis"),
    ]

    operations = [
        migrations.AddField(
            model_name="nivelaprovacao",
            name="funcao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="niveis_aprovacao",
                to="users.funcao",
                verbose_name="Função Aprovadora",
            ),
        ),
        migrations.RunPython(migrar_funcao_para_nivel, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="AprovadorNivel",
        ),
    ]
