# Generated by Django 5.2 on 2026-06-13 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0014_nivelaprovacao_funcao_delete_aprovadornivel"),
        ("users", "0030_fix_remove_papeis"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="nivelaprovacao",
            unique_together={("fluxo", "funcao"), ("fluxo", "ordem")},
        ),
    ]
