# Generated by Django 5.2 on 2026-06-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0015_alter_nivelaprovacao_unique_together"),
        ("users", "0030_fix_remove_papeis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aprovacaorequisicao",
            name="aprovador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votos_aprovacao",
                to="users.usuario",
                verbose_name="Aprovador",
            ),
        ),
        migrations.AlterField(
            model_name="fluxoaprovacao",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.usuario",
                verbose_name="Criado por",
            ),
        ),
    ]
