# Generated by Django 4.2.30 on 2026-06-23 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0022_multi_tenant'),
        ('financeiro', '0016_alter_aprovacaorequisicao_aprovador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacliente',
            name='banca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas_cliente', to='rh.banca'),
        ),
        migrations.AddField(
            model_name='facturacliente',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_cliente', to='rh.filialbanca'),
        ),
        migrations.AddField(
            model_name='facturarecibo',
            name='banca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas_recibo', to='rh.banca'),
        ),
        migrations.AddField(
            model_name='facturarecibo',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_recibo', to='rh.filialbanca'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='banca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito', to='rh.banca'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito', to='rh.filialbanca'),
        ),
        migrations.AddField(
            model_name='notadebito',
            name='banca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas_debito', to='rh.banca'),
        ),
        migrations.AddField(
            model_name='notadebito',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_debito', to='rh.filialbanca'),
        ),
        migrations.AddField(
            model_name='recibocliente',
            name='banca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recibos_cliente', to='rh.banca'),
        ),
        migrations.AddField(
            model_name='recibocliente',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibos_cliente', to='rh.filialbanca'),
        ),
        migrations.AddField(
            model_name='requisicaofundo',
            name='banca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes_fundo', to='rh.banca'),
        ),
        migrations.AddField(
            model_name='requisicaofundo',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_fundo', to='rh.filialbanca'),
        ),
        migrations.AlterField(
            model_name='recibocliente',
            name='estado',
            field=models.CharField(blank=True, choices=[('Pendente', 'Pendente'), ('Cancelado', 'Cancelado')], db_index=True, default='Pendente', max_length=20, null=True, verbose_name='Estado'),
        ),
    ]
