# Generated by Django 4.2.30 on 2026-06-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0023_alter_processamentosalarial_unique_together_and_more'),
        ('financeiro', '0017_multi_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxoaprovacao',
            name='banca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fluxos_aprovacao', to='rh.banca', verbose_name='Banca'),
        ),
        migrations.AddField(
            model_name='historicofinanceiro',
            name='banca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_financeiros', to='rh.banca', verbose_name='Banca'),
        ),
        migrations.AddField(
            model_name='historicofinanceiro',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_financeiros', to='rh.filialbanca', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='nivelaprovacao',
            name='banca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='niveis_aprovacao', to='rh.banca', verbose_name='Banca'),
        ),
    ]
