# Generated by Django 4.2.30 on 2026-06-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0018_fluxoaprovacao_banca_historicofinanceiro_banca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprovacaorequisicao',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='facturacliente',
            name='criado_por_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID do Criador'),
        ),
        migrations.AlterField(
            model_name='facturacliente',
            name='data_emissao',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='facturarecibo',
            name='data',
            field=models.DateField(db_index=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='facturarecibo',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='facturarecibo',
            name='forma_pagamento',
            field=models.CharField(choices=[('Transferência Bancária', 'Transferência Bancária'), ('Multicaixa', 'Multicaixa'), ('TPAs', 'TPAs'), ('Depósito Bancário', 'Depósito Bancário'), ('Numerário', 'Numerário')], db_index=True, max_length=50, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='fluxoaprovacao',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='fluxoaprovacao',
            name='nome',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nome do Fluxo'),
        ),
        migrations.AlterField(
            model_name='nivelaprovacao',
            name='nome',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nome do Nível'),
        ),
        migrations.AlterField(
            model_name='nivelaprovacao',
            name='ordem',
            field=models.PositiveSmallIntegerField(db_index=True, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='data',
            field=models.DateField(db_index=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='data',
            field=models.DateField(db_index=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='recibocliente',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='recibocliente',
            name='data_pagamento',
            field=models.DateField(db_index=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AlterField(
            model_name='recibocliente',
            name='forma_pagamento',
            field=models.CharField(choices=[('Transferência Bancária', 'Transferência Bancária'), ('Multicaixa', 'Multicaixa'), ('TPAs', 'TPAs'), ('Depósito Bancário', 'Depósito Bancário'), ('Numerário', 'Numerário')], db_index=True, max_length=50, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='requisicaofundo',
            name='nivel_atual',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Nível Actual'),
        ),
        migrations.AlterField(
            model_name='requisicaofundo',
            name='solicitante_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID do Solicitante'),
        ),
    ]
