# Generated by Django 4.2.30 on 2026-06-28 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0020_ativofixo_orcamento_planocontas_lancamentocontabil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaativo',
            name='banca',
        ),
        migrations.AlterUniqueTogether(
            name='depreciacao',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='depreciacao',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='depreciacao',
            name='lancamento_contabil',
        ),
        migrations.RemoveField(
            model_name='lancamentocontabil',
            name='banca',
        ),
        migrations.RemoveField(
            model_name='lancamentocontabil',
            name='conta_credito',
        ),
        migrations.RemoveField(
            model_name='lancamentocontabil',
            name='conta_debito',
        ),
        migrations.RemoveField(
            model_name='lancamentocontabil',
            name='filial',
        ),
        migrations.AlterUniqueTogether(
            name='orcamento',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='banca',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='filial',
        ),
        migrations.AlterUniqueTogether(
            name='orcamentoitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='orcamentoitem',
            name='conta',
        ),
        migrations.RemoveField(
            model_name='orcamentoitem',
            name='orcamento',
        ),
        migrations.AlterUniqueTogether(
            name='planocontas',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='planocontas',
            name='banca',
        ),
        migrations.RemoveField(
            model_name='planocontas',
            name='conta_pai',
        ),
        migrations.AlterUniqueTogether(
            name='saldoconta',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='saldoconta',
            name='banca',
        ),
        migrations.RemoveField(
            model_name='saldoconta',
            name='conta',
        ),
        migrations.DeleteModel(
            name='AtivoFixo',
        ),
        migrations.DeleteModel(
            name='CategoriaAtivo',
        ),
        migrations.DeleteModel(
            name='Depreciacao',
        ),
        migrations.DeleteModel(
            name='LancamentoContabil',
        ),
        migrations.DeleteModel(
            name='Orcamento',
        ),
        migrations.DeleteModel(
            name='OrcamentoItem',
        ),
        migrations.DeleteModel(
            name='PlanoContas',
        ),
        migrations.DeleteModel(
            name='SaldoConta',
        ),
    ]
