# Generated by Django 4.2.30 on 2026-07-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0022_novo_requisicao_fundo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluxoaprovacao',
            name='banca',
        ),
        migrations.RemoveField(
            model_name='fluxoaprovacao',
            name='criado_por',
        ),
        migrations.AlterUniqueTogether(
            name='nivelaprovacao',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='nivelaprovacao',
            name='banca',
        ),
        migrations.RemoveField(
            model_name='nivelaprovacao',
            name='fluxo',
        ),
        migrations.RemoveField(
            model_name='nivelaprovacao',
            name='funcao',
        ),
        migrations.DeleteModel(
            name='AprovacaoRequisicao',
        ),
        migrations.DeleteModel(
            name='FluxoAprovacao',
        ),
        migrations.DeleteModel(
            name='NivelAprovacao',
        ),
    ]
