# Generated by Django 4.2.30 on 2026-07-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0023_remove_fluxoaprovacao_banca_and_more'),
    ]

    operations = [
        # Only remove if the field exists - handle the case where it was already removed
        migrations.RunSQL(
            sql="ALTER TABLE `financeiro_requisicao_fundo` DROP COLUMN IF EXISTS `nivel_atual`;",
            reverse_sql="-- Field removed",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE `financeiro_requisicao_fundo` DROP COLUMN IF EXISTS `fluxo_aprovacao_id`;",
            reverse_sql="-- Field removed",
        ),
    ]
