# Generated by Django 4.2.30 on 2026-07-06 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0026_fix_requisicaofundo_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibocliente',
            name='requisicao_fundo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibos_pagamento', to='financeiro.requisicaofundo', verbose_name='Requisição de Fundo'),
        ),
    ]
