# Generated by Django 4.2.30 on 2026-07-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0027_add_requisicao_fundo_to_recibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacliente',
            name='requisicao_fundo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='financeiro.requisicaofundo', verbose_name='Requisição de Fundos'),
        ),
        migrations.AlterField(
            model_name='requisicaofundo',
            name='estado',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aceite', 'Aceite'), ('Rejeitada', 'Rejeitada'), ('Anulada', 'Anulada')], db_index=True, default='Pendente', max_length=20, verbose_name='Estado'),
        ),
    ]
