# Generated by Django 4.2.30 on 2026-07-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0028_facturacliente_requisicao_fundo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaofundolinha',
            name='tipo_custo',
            field=models.CharField(choices=[('Impostos e Taxas Aduaneiras (AGT)', 'Impostos e Taxas Aduaneiras (AGT)'), ('Despesas Portuárias e Terminais', 'Despesas Portuárias e Terminais'), ('Logística e Transporte', 'Logística e Transporte'), ('Honorários do Despachante', 'Honorários do Despachante'), ('Outras Despesas', 'Outras Despesas')], db_index=True, max_length=50, verbose_name='Tipo de Custo'),
        ),
    ]
