# Generated by Django 4.2.30 on 2026-07-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0030_fix_iva_retencao_calculation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='facturacliente',
            index=models.Index(fields=['cliente', 'estado'], name='ix_factura_cliente_estado'),
        ),
        migrations.AddIndex(
            model_name='facturacliente',
            index=models.Index(fields=['banca', 'filial'], name='ix_factura_banca_filial'),
        ),
        migrations.AddIndex(
            model_name='facturarecibo',
            index=models.Index(fields=['cliente', 'estado'], name='ix_fr_cliente_estado'),
        ),
        migrations.AddIndex(
            model_name='facturarecibo',
            index=models.Index(fields=['factura', 'estado'], name='ix_fr_factura_estado'),
        ),
        migrations.AddIndex(
            model_name='facturarecibo',
            index=models.Index(fields=['banca', 'filial'], name='ix_fr_banca_filial'),
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['cliente', 'data', 'estado'], name='ix_nc_cliente_data_estado'),
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['banca', 'filial'], name='ix_nc_banca_filial'),
        ),
        migrations.AddIndex(
            model_name='notadebito',
            index=models.Index(fields=['cliente', 'data', 'estado'], name='ix_nd_cliente_data_estado'),
        ),
        migrations.AddIndex(
            model_name='notadebito',
            index=models.Index(fields=['banca', 'filial'], name='ix_nd_banca_filial'),
        ),
        migrations.AddIndex(
            model_name='recibocliente',
            index=models.Index(fields=['cliente', 'estado'], name='ix_recibo_cliente_estado'),
        ),
        migrations.AddIndex(
            model_name='recibocliente',
            index=models.Index(fields=['factura', 'estado'], name='ix_recibo_factura_estado'),
        ),
        migrations.AddIndex(
            model_name='recibocliente',
            index=models.Index(fields=['banca', 'filial'], name='ix_recibo_banca_filial'),
        ),
        migrations.AddIndex(
            model_name='requisicaofundo',
            index=models.Index(fields=['banca', 'filial'], name='ix_rf_banca_filial'),
        ),
        migrations.AddIndex(
            model_name='requisicaofundolinha',
            index=models.Index(fields=['requisicao', 'tipo_custo'], name='ix_rfl_requisicao_tipo'),
        ),
        migrations.AlterModelTable(
            name='requisicaofundolinha',
            table='financeiro_requisicao_linha',
        ),
    ]
