# Generated by Django 4.2.30 on 2026-07-08 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0031_facturacliente_ix_factura_cliente_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturarecibo',
            name='requisicao_fundo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_recibo', to='financeiro.requisicaofundo', verbose_name='Requisição de Fundos'),
        ),
    ]
