# Generated by Django 4.2.30 on 2026-07-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0032_fr_requisicao_fundo_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicaofundo',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='requisicaofundo',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='requisicaofundo',
            name='numero_conta',
        ),
    ]
