# Generated by Django 4.2.30 on 2026-07-09 17:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0035_add_linha_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacliente',
            name='retencao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Retenção'),
        ),
    ]
