# Generated by Django 4.2.30 on 2026-07-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0036_facturacliente_retencao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaofundolinha',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição'),
        ),
    ]
