# Generated by Django 4.2.30 on 2026-07-10 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0037_alter_requisicaofundolinha_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacredito',
            name='factura_relacionada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='financeiro.facturacliente', verbose_name='Factura Relacionada'),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='factura_relacionada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_debito', to='financeiro.facturacliente', verbose_name='Factura Relacionada'),
        ),
        migrations.AlterField(
            model_name='recibocliente',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='financeiro.facturacliente', verbose_name='Factura'),
        ),
    ]
