# Generated by Django 4.2.30 on 2026-07-11 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_alter_cliente_saldo_conta_corrente'),
        ('financeiro', '0038_alter_notacredito_factura_relacionada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_cliente', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='facturarecibo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_recibo', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='factura_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito', to='financeiro.facturacliente', verbose_name='Factura Relacionada'),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_debito', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='factura_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_debito', to='financeiro.facturacliente', verbose_name='Factura Relacionada'),
        ),
        migrations.AlterField(
            model_name='recibocliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos_cliente', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='recibocliente',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibos', to='financeiro.facturacliente', verbose_name='Factura'),
        ),
        migrations.AlterField(
            model_name='requisicaofundo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_fundos', to='clientes.cliente', verbose_name='Cliente'),
        ),
    ]
