# Generated by Django 4.2.30 on 2026-07-11 21:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0039_alter_facturacliente_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacliente',
            name='ajuste_nota_credito',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Ajuste por Nota de Crédito'),
        ),
        migrations.AddField(
            model_name='facturacliente',
            name='ajuste_nota_debito',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Ajuste por Nota de Débito'),
        ),
    ]
