# Generated by Django 4.2.30 on 2026-07-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0040_facturacliente_ajuste_nota_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaofundo',
            name='taxa_iva',
            field=models.CharField(choices=[('14', '14% - Regime Geral'), ('6.5', '6,5% - Regime Simplificado')], default='14', max_length=5, verbose_name='Taxa de IVA'),
        ),
    ]
