# Generated by Django 4.2.30 on 2026-07-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0040_remove_iva_honorarios'),
        ('financeiro', '0041_requisicaofundo_taxa_iva'),
    ]

    operations = [
    ]
