# Generated by Django 4.2.30 on 2026-08-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0043_add_iva_honorarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaofundo',
            name='taxa_iva',
            field=models.CharField(choices=[('14', '14% - Regime Geral (IVA)'), ('6.5', '6,5% - Regime Simplificado (Retenção)')], default='14', max_length=5, verbose_name='Regime'),
        ),
    ]
