# Generated by Django 5.2 on 2026-06-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_add_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="usuario_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="ID do Despachante"
            ),
        ),
    ]
