# Generated by Django 5.2 on 2026-06-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0004_alter_cliente_ativo_alter_cliente_usuario_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="usuario_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID do Despachante"
            ),
        ),
    ]
