# Generated by Django 5.2 on 2026-06-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0005_alter_cliente_usuario_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="limite_financeiro",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=15,
                verbose_name="Limite Financeiro por Cliente",
            ),
        ),
    ]
