# Generated by Django 5.2 on 2026-06-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0006_cliente_limite_financeiro"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="saldo_conta_corrente",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=15,
                verbose_name="Saldo da Conta Corrente",
            ),
        ),
    ]
