# Generated by Django 5.2 on 2026-06-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0007_cliente_saldo_conta_corrente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="ativo",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Ativo"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                default="",
                max_length=254,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nome",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Nome do Cliente"
            ),
        ),
    ]
