# Generated by Django 4.2.30 on 2026-06-23 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0022_multi_tenant'),
        ('clientes', '0008_add_nome_email_ativo_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='banca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='rh.banca'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='rh.filialbanca'),
        ),
    ]
