# Generated by Django 4.2.30 on 2026-06-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_multi_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='Telefone'),
        ),
    ]
