# Generated by Django 4.2.30 on 2026-07-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_alter_cliente_criado_em_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='saldo_conta_corrente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo da Conta Corrente'),
        ),
    ]
